### ISSUE TITLE
Fix UI for Light/Dark theme button

### ISSUE THREAD

**Issue by hgjajoo** [PriyaGhosal/BuddyTrail#1]
![image](https://github.com/user-attachments/assets/60c09adf-0e26-4b73-be08-8cf5a0a7bc81)
Fixing this UI

can assign me!

**Comment by PriyaGhosal** [comment]
@hgjajoo Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by hgjajoo** [comment]
sent a pr
