### ISSUE TITLE
UI and Layout Enhancements for Travel Application

### ISSUE THREAD

**Issue by Kavish-Paraswar** [PriyaGhosal/BuddyTrail#100]
There should be more space between the "Book a Cab" section and the "Travel Itinerary" section to avoid a cluttered look.
![image](https://github.com/user-attachments/assets/efa1c301-54fd-4c31-b2a0-eb34baf831b4)

The input boxes in the "Book a Cab or Auto" section have poor design. They need to be improved by refining the box style and adding appropriate spacing between them. Additionally, they should be aligned centrally for a balanced appearance.
![image](https://github.com/user-attachments/assets/e102a718-639c-4c47-97e5-3a7927d0e123)

The font size in the "Personalized Recommendation" section is not appropriate and does not match the overall UI style, which affects the page's visual harmony.
![image](https://github.com/user-attachments/assets/125880c5-26d1-4456-a694-b13a8e164956)

Reducing the length will improve the overall layout and provide a more polished look.
![image](https://github.com/user-attachments/assets/9533e384-9523-4c51-9898-b16653634d88)

Given my strong background in HTML, CSS, and JavaScript, I would like to request that this task be assigned to me. I intend to mark this under the GSoC extended projects and level 2 atleast .

**Comment by PriyaGhosal** [comment]
@Kavish-Paraswar Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by Kavish-Paraswar** [comment]
Please mark the issue as at least level 2, as I will be dealing with 4-5 issues along with additional smaller issues.

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me
