### ISSUE TITLE
changes in the Destination Guides form

### ISSUE THREAD

**Issue by Sivasaiklu** [PriyaGhosal/BuddyTrail#1049]
![image](https://github.com/user-attachments/assets/8dd8c26b-47ca-482e-b563-c98b33ef7188)

=> Destination Guides form is not effective, we have to change the interface for the form

**Comment by pynaman** [comment]
@Sivasaiklu Hey! Are you still working on this issue? Can I work on this?

**Comment by Sivasaiklu** [comment]
This issue is solved, I am closing
