### ISSUE TITLE
Travel Itineraries & Book a Cab or Auto UI Improvment

### ISSUE THREAD

**Issue by NishantK-07** [PriyaGhosal/BuddyTrail#105]
The Travel Itineraries & Book a Cab or Auto can be improved for a better User Interaction and better UI Designing
![Screenshot 2024-10-05 145131](https://github.com/user-attachments/assets/e3909057-e92f-4ae1-8cb3-a920af2e490e)
![Screenshot 2024-10-05 144810](https://github.com/user-attachments/assets/24e4a12a-f929-4639-a684-d0b5fc83cf59)

**Comment by NishantK-07** [comment]
Please assign this issue to me under gssoc ext 2024 ..........

**Comment by PriyaGhosal** [comment]
@NishantK-07 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
