### ISSUE TITLE
Better scrollbar and progressbar

### ISSUE THREAD

**Issue by srishti023** [PriyaGhosal/BuddyTrail#107]
I want to make better scrollbarand progress bar that looks good with the website UI 
please assign me with hacktoberfest, gssoc24-ext label.
Thankyou!

**Comment by PriyaGhosal** [comment]
@srishti023 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by srishti023** [comment]
Hi @PriyaGhosal,

I wanted to let you know that I’ve added the new better scroll bar and progress bar to the website. please let me know if you want any change else accept my pull request!
Thank you
Best Regards!
