### ISSUE TITLE
BUG: Make this copyright visible 

### ISSUE THREAD

**Issue by PriyaGhosal** [PriyaGhosal/BuddyTrail#1073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### DIRECTLY CREATE PR ... IT WILL BE ASSIGNED IN THIS ISSUE LATER

![image](https://github.com/user-attachments/assets/40a0fce2-e73b-467c-a9d3-6c91a6383c05)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by AADESHak007** [comment]
Hey @PriyaGhosal  I have raised PR which will solve this issue . Please check  PR #1086 and merge it .
