### ISSUE TITLE
DOC: ADD PRIVACY POLICY PAGE

### ISSUE THREAD

**Issue by PriyaGhosal** [PriyaGhosal/BuddyTrail#1074]
### DIRECTLY CREATE PR ... IT WILL BE ASSIGNED IN THIS ISSUE LATER

![image](https://github.com/user-attachments/assets/82eda827-1220-4522-9397-37d2707d8422)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by snehhhcodes** [comment]
@PriyaGhosal assign it to me i can make you one
