### ISSUE TITLE
Improve the UI of Exclusive deals section

### ISSUE THREAD

**Issue by Aradhya-005** [PriyaGhosal/BuddyTrail#108]
![image](https://github.com/user-attachments/assets/e5c64ae2-849d-49d9-baf6-cffd55bc7968)
the container of this section are not align properly and not looking visually appealing. 
So i would like to improve the UI and alignment of these container. 
@PriyaGhosal  Please assign this task to ne under GSSoC extended and Hacktoberfest

**Comment by PriyaGhosal** [comment]
@Aradhya-005 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
