### ISSUE TITLE
Navbar overlaps with main content

### ISSUE THREAD

**Issue by Jerusha547** [PriyaGhosal/BuddyTrail#109]
When navigating the website by clicking on links in the Navbar, parts of the content are hidden behind the navbar. The appropriate padding or offset is not applied to the content.
After clicking a Navbar link, the content should be fully visible below the Navbar, without any overlap.
There should be a proper margin or padding between the Navbar and the content, ensuring that all sections are accessible.
I will make sure to resolve this issue.

**Comment by PriyaGhosal** [comment]
@Jerusha547 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me
