### ISSUE TITLE
bug : checkout deals 

### ISSUE THREAD

**Issue by Risheendra183** [PriyaGhosal/BuddyTrail#11]
after clicking the checkout deals it does not disappear and the interface is not good for exclusive -deals -offers card.
I will do this please assign me
![image](https://github.com/user-attachments/assets/b6dd781d-deea-4c1b-9320-28a4f9fc798e)
![image](https://github.com/user-attachments/assets/3449e6dd-bd7d-43a3-b343-d020f4ac07e4)

**Comment by PriyaGhosal** [comment]
@Risheendra183 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
