### ISSUE TITLE
BUG: Implement Hover Override Effect in Destination Guide Section

### ISSUE THREAD

**Issue by KAJAL7764** [PriyaGhosal/BuddyTrail#1109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Issues**
Implement Hover Override Effect in Destination Guide Section

**Descriptions**
When users hover over the "Destination Guide" section, the content expands and occupies additional space above the section. This behavior disrupts the overall layout and creates a confusing user experience.

![align](https://github.com/user-attachments/assets/d9b1cc91-120e-4dde-aedf-e6b59ed3b2f8)

Labels: UX-improvement/enhancement

Could you Please assign me this task so that I can work on improving the hover functionality in the "Destination Guide" section

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sunidhi3** [comment]
Please assign this to me i can work on it I'm a GSSoC contributor
