### ISSUE TITLE
Fix Overlapping and Excessive Size of Footer in About Us Section

### ISSUE THREAD

**Issue by ayusharyan143** [PriyaGhosal/BuddyTrail#1134]
## Description:
The footer in the "About Us" section is overlapping and covers a significant portion of the page, making it difficult for users to navigate. Additionally, the footer is not displaying correctly on smaller devices, affecting the overall user experience.

![image](https://github.com/user-attachments/assets/3e45488e-d6dc-4d6f-93ad-337dcfb13870)
![image](https://github.com/user-attachments/assets/76842087-6a33-423c-bf8c-2dc86cb25f6b)

## Expected Behavior:
The footer should have a consistent and appropriate size that does not cover the entire page.
Elements within the footer should be properly spaced and aligned.
The footer should be responsive and display correctly on small devices.

## Additional Information:
Please assign this issue to me, as I would like to work on implementing the necessary fixes.

**Comment by Vanshika-OFFICIAL** [comment]
Please assign it to me.
