### ISSUE TITLE
Enhance Rating UI with Star Click Buttons

### ISSUE THREAD

**Issue by ananyag309** [PriyaGhosal/BuddyTrail#116]
Replaced the dropdown rating option with clickable star buttons to provide a more intuitive and visually appealing rating system, improving the overall user experience.
![rating form](https://github.com/user-attachments/assets/1d68a63a-74b2-4ce5-b68c-47b27fc0fba0)

**Comment by dwivedishrey** [comment]
@ananyag309  I’ve assigned this issue to you. Please go ahead and start working on it.

**Comment by ananyag309** [comment]
@dwivedishrey yes sure thankyou for assigning me the issue
