### ISSUE TITLE
Want to improve the design of Exclusive Deals and Offers, Travel Itineraries, and Personalized Recommendations sections.

### ISSUE THREAD

**Issue by Mr-DK07** [PriyaGhosal/BuddyTrail#117]
I proposed to improve the design of the card and other part of these section like (Font size, color, etc ).
So that UI/UX of website looks good and also align with existing website.

![Screenshot 2024-10-05 232341](https://github.com/user-attachments/assets/c57782be-48c6-4b39-b7cd-81d60e87e67a)
![Screenshot 2024-10-05 232355](https://github.com/user-attachments/assets/1619922b-50c0-4792-8229-b7e68389094e)
![Screenshot 2024-10-05 232409](https://github.com/user-attachments/assets/8291bbeb-482b-4c0a-9d3e-b0264c9d2c1c)

@PriyaGhosal  Could you assign me this, so I cant start working on it.
Please ensure that to add labels on it.

**Comment by dwivedishrey** [comment]
@Mr-DK07 I’ve assigned this issue to you. Please go ahead and start working on it
