### ISSUE TITLE
Improve booking section

### ISSUE THREAD

**Issue by poorvikaa08** [PriyaGhosal/BuddyTrail#118]
Changes to be made:
* Improve alignment of this section
* Enhance it's styling for better user- interface

Screenshot 📸 
![image](https://github.com/user-attachments/assets/96a55c79-5804-42a7-811f-c7e5954f39a0)

I would like to work on this issue under gssoc24 and hacktoberfest
@PriyaGhosal Can you assign it to me?
Thank you.

**Comment by dwivedishrey** [comment]
@poorvikaa08 I’ve assigned this issue to you. Please go ahead and start working on it.

**Comment by poorvikaa08** [comment]
@dwivedishrey Thanks for assigning me. I will work on it
