### ISSUE TITLE
better bottom most container 

### ISSUE THREAD

**Issue by sureshkushwaha123** [PriyaGhosal/BuddyTrail#120]
![image](https://github.com/user-attachments/assets/9ee93618-5e3f-4a78-b560-491231bbaa4f)
I would like to improve this section as it does not look so attractive and also missing some basic information like the **contact area, legal area containing terms and policies**. Also, size the **social media logos**. Most importantly all rights reserved are missing with the current year. 
Also, a **language section** is needed in this area. 
I would love to work on this project.

**Comment by PriyaGhosal** [comment]
@sureshkushwaha123 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
