### ISSUE TITLE
BUG: README CONTRIBUTORS ERROR

### ISSUE THREAD

**Issue by PriyaGhosal** [PriyaGhosal/BuddyTrail#1227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### DIRECTLY CREATE PR ... IT WILL BE ASSIGNED IN THIS ISSUE LATER
Only certain contributors pictures are present at the of readme. 
![image](https://github.com/user-attachments/assets/f1dbcebc-617b-4e47-b5c6-599027153e88)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by yashksaini-coder** [comment]
@PriyaGhosal I want to work on this issue can you assign it to me
