### ISSUE TITLE
Documentation of Contributing.md

### ISSUE THREAD

**Issue by ark0078** [PriyaGhosal/BuddyTrail#124]
Can you please assign me to work on documenting Contribution.md ??please @sanjay-kv @hgjajoo @dwivedishrey @hritika2409 @Archisman141

**Comment by Archisman141** [comment]
> Can you please assign me to work on documenting Contribution.md ??please @sanjay-kv @hgjajoo @dwivedishrey @hritika2409 @Archisman141 

Ask @PriyaGhosal mam to assign you the task

**Comment by ark0078** [comment]
> > Can you please assign me to work on documenting Contribution.md ??please @sanjay-kv @hgjajoo @dwivedishrey @hritika2409 @Archisman141
> 
> Ask @PriyaGhosal mam to assign you the task

Already asked and tagged

**Comment by ark0078** [comment]
btw,thanks

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.

**Comment by PriyaGhosal** [comment]
@ark0078 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
