### ISSUE TITLE
Inconsistent Discount Calculation Across Packages

### ISSUE THREAD

**Issue by PATILYASHH** [PriyaGhosal/BuddyTrail#126]
**Description:**
I noticed a discrepancy in the pricing discounts offered on the travel packages. While browsing through the packages, I observed that the percentage of discounts applied is inconsistent across the packages:

- **Kerala Backwaters Package**: Original price ₹50,000, discounted to ₹40,000 (a 20% discount).
- **Paris Romantic Getaway**: Original price ₹1,50,000, discounted to ₹1,20,000 (a 20% discount).
- **Adventure in Bali**: Original price ₹60,000, discounted to ₹48,000 (a 20% discount).

The current discounts seem arbitrary, and there doesn't appear to be a fixed percentage being applied. For a more user-friendly experience, I suggest applying a consistent discount percentage across all packages. For example, if all packages are meant to have a 20% discount, this should be reflected uniformly.

**Steps to Reproduce:**
1. Navigate to the travel packages section.
2. Compare the original prices and discounted prices across different packages.

**Expected Behavior:**
The discount percentage applied to the packages should follow a consistent pattern. If the intended discount is 20%, this should be applied uniformly across all packages.

**Actual Behavior:**
The discounts seem inconsistent, which may confuse users regarding the actual value they are saving.

**Suggested Fix:**
Ensure that the same percentage of discount is applied to all packages or clarify the discount logic on the website if the variation is intentional.

**Screenshot**
![Screenshot_2024_1006_072955.jpg](https://github.com/user-attachments/assets/01b58004-30ec-4aba-923d-e495ec0f39e0)

**Comment by PATILYASHH** [comment]
Please assign me for this issue

**Comment by PriyaGhosal** [comment]
@PATILYASHH @ark0078 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by PATILYASHH** [comment]
What is the level of this issue
