### ISSUE TITLE
BUG:The contents in the card are not completely visible 

### ISSUE THREAD

**Issue by pa1narendra** [PriyaGhosal/BuddyTrail#1262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we first visit the site , the signup/signin form is looking like this
![image](https://github.com/user-attachments/assets/d19c7e14-4077-4fd0-8f67-362b68068074)

I will modify the page and get this done

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pc-daukiya** [comment]
i want to do this, I can more upgrade this signup page.
