### ISSUE TITLE
ENHANCING UI OF FOOTER

### ISSUE THREAD

**Issue by anusuyasri** [PriyaGhosal/BuddyTrail#13]
![image](https://github.com/user-attachments/assets/6567e2a7-4b57-4afb-bac9-d5f06bd56685)
##
Responsive UI- Responsive web design, is a web development approach that ensures a website works well on different devices and screen sizes. It's a key part of user interface (UI) design and user experience (UX).
Favicons are used in a variety of places in a user interface (UI) to help users identify a website, and they can improve user experience and search engine optimization (SEO).With google icons and material UI I can Improve the look.
While improving the background of the footer I can also add hover effect,other missing sections like contact us,destinations,logo and various other options.
The alignment of the icons could be made better to make the overall look more visually appealing.
Please assign this issue to me.
Thank you

**Comment by hritika2409** [comment]
Please assign me this task

**Comment by PriyaGhosal** [comment]
@anusuyasri Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by PriyaGhosal** [comment]
@hritika2409 Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!
