### ISSUE TITLE
Adding Login Page for Enhanced User Authentication

### ISSUE THREAD

**Issue by IshaRawat7** [PriyaGhosal/BuddyTrail#130]
Hii @PriyaGhosal , I would like to contribute to the project by creating a login page. Currently, there is no login functionality, which is essential for user authentication and security.
Here is my input below:-
User details Fields: Fields for entering name,username and password.
UI/UX Design: A user-friendly and visually appealing design for the login page.
Also, the CONTACT US page is not visually appealing , we can add some more input fields to it.

![Screenshot 2024-10-06 100803](https://github.com/user-attachments/assets/8f129201-7dd7-46bd-88cc-d68f3d9085cd)

**Comment by PriyaGhosal** [comment]
@IshaRawat7 @ark0078 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by IshaRawat7** [comment]
Thank you @PriyaGhosal ,I will start working now.
