### ISSUE TITLE
Images not displaying in Readme.md file

### ISSUE THREAD

**Issue by neeru24** [PriyaGhosal/BuddyTrail#132]
Hi, In the readme.md file.. these images are not showing... I would like to add the screenshots from the website here and fix it.

![image](https://github.com/user-attachments/assets/2615f23c-626a-4f12-80dd-1ff0b59eb289)

**Comment by PriyaGhosal** [comment]
@neeru24 @ark0078 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by neeru24** [comment]
> @neeru24 @ark0078 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.
> 
> Before you start working on your PR, please make sure to:
> 
> - ⭐ Star the repository if you haven't already.
> - Pull the latest changes to avoid any merge conflicts.
> - Attach *before & after screenshots* in your PR for clarity.
> - Include the *issue number* in your PR description for better tracking.
> 
> Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!
> 
> I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
> Don't forget to follow me on GitHub for more updates.
> 
> Happy open-source contributing! 🚀

Done with the changes 👍
