### ISSUE TITLE
Improving UI of full home page

### ISSUE THREAD

**Issue by Anamika-garg** [PriyaGhosal/BuddyTrail#134]
The UI of home page looks sick and i would like to make it a bit modern and good to eyes. Kindly assign this task to me

![Uploading Screenshot (269).png…]()

**Comment by PriyaGhosal** [comment]
@Anamika-garg @ark0078 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
