### ISSUE TITLE
Design Improvements

### ISSUE THREAD

**Issue by yasheela-alla** [PriyaGhosal/BuddyTrail#136]
I want To improve the cab or auto booking interface

![image](https://github.com/user-attachments/assets/2889bd49-3c2f-46ee-97e7-f22890446512)

@PATILYASHH @PriyaGhosal Please assign this to me. I'd love to work on this.

**Comment by PriyaGhosal** [comment]
@yasheela-alla @ark0078 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by yasheela-alla** [comment]
@PriyaGhosal this issue was taken by someone else, and they already improved the UI, why did you assign me then? do you still me to improve this? 

![image](https://github.com/user-attachments/assets/b4c12684-2be2-4e0b-8147-f1afe4f101ff)

**Comment by yasheela-alla** [comment]
@PriyaGhosal Since the issue i raised was already improved, i did few design enhancements in footer section, if you're okay with that, I will pull a merge request.

**Comment by yasheela-alla** [comment]
@PriyaGhosal can you please confirm?
