### ISSUE TITLE
Navbar needs Improvement

### ISSUE THREAD

**Issue by AbhinabPalei** [PriyaGhosal/BuddyTrail#137]
The Navbar is very simple its need improvement for better UI @PriyaGhosal can you please assign me this issue under GSSoC-extd

**Comment by PriyaGhosal** [comment]
@AbhinabPalei @ark0078 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
