### ISSUE TITLE
Updating the Navbar

### ISSUE THREAD

**Issue by hritika2409** [PriyaGhosal/BuddyTrail#14]
<img width="938" alt="image" src="https://github.com/user-attachments/assets/8b338993-8451-4678-8fbe-abd8399b48c7">

**Comment by namami-13** [comment]
I want to work on this task. Please give me confirmation to work on it.

**Comment by rajatsinghal02** [comment]
@PriyaGhosal Please assign this issue to me. I want to work on this issue.

**Comment by PriyaGhosal** [comment]
@hritika2409 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
