### ISSUE TITLE
BUG: In FAQ page the image is not visible

### ISSUE THREAD

**Issue by Ashish-Patnaik** [PriyaGhosal/BuddyTrail#1401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the FAQ page the images is not properly aligned due to this the page looks misaligned. Please assign me i will fix the issue as soon as possible
![999](https://github.com/user-attachments/assets/95b16670-9b0c-42d4-a0ed-057e7066e6b8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AbrerAsif07** [comment]
Can you assign me this issue?
