### ISSUE TITLE
in the Exclusive Deals and Offers cards do not have any kind of effect on that 

### ISSUE THREAD

**Issue by tusharmishra069** [PriyaGhosal/BuddyTrail#143]
in the Exclusive Deals and Offers cards do not have any kind of effect on that , like the hover effect, zoom in effect and something like that , and it very much appreciable for me if a complete this , and i love to complete this and contribute to your project

**Comment by PriyaGhosal** [comment]
@tusharmishra069 @ark0078 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
