### ISSUE TITLE
Add Hamburger Menu for Navbar on Mobile Devices

### ISSUE THREAD

**Issue by srishti023** [PriyaGhosal/BuddyTrail#146]
The current navigation bar lacks a hamburger menu for mobile devices, affecting the overall user experience on smaller screens. To improve responsiveness, I propose adding a hamburger menu that toggles the navigation links when viewed on mobile devices.

Please assign me with gssoc-ext and hacktoberfest tag . i want to work on this project!
Thankyou!

**Comment by PriyaGhosal** [comment]
@srishti023 @ark0078 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
