### ISSUE TITLE
add a button to scroll back to the top

### ISSUE THREAD

**Issue by ShrishtiSingh26** [PriyaGhosal/BuddyTrail#15]
I wish to add a button to scroll back to the top of the page
please assign this issue

**Comment by Kratika-Solanki** [comment]
@PriyaGhosal, I want to work on this..

**Comment by PriyaGhosal** [comment]
@Kratika-Solanki Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by PriyaGhosal** [comment]
@ShrishtiSingh26 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
