### ISSUE TITLE
Feat: Adding  Close (X)  Button To Pop-up.

### ISSUE THREAD

**Issue by Nelcy17** [PriyaGhosal/BuddyTrail#1509]
### Describe the feature

**Currently  the pop-up can be dismissed on clicking "No Thanks". I want to add a close button on top right corner of pop-up.**

It will Improve User Experience and Ease of Use as users can quickly close the pop-up without searching for the "No thanks" button.

It will give users more control over their interaction with the site, making the experience better.

It will make the design appear more professional.

### Add ScreenShots

![Screenshot-popup](https://github.com/user-attachments/assets/ffe30301-52e3-4480-900a-37c1485f3c6d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kartik-212004** [comment]
I would like to resolve this issue. Please assign it to me.
Thanks

**Comment by ShirshenduR** [comment]
please assign me

**Comment by manastiwari99** [comment]
I would like too work Please assign it  to me
