### ISSUE TITLE
🌟 Lacking Testimonial page

### ISSUE THREAD

**Issue by 1ShahidBashir** [PriyaGhosal/BuddyTrail#152]
@PriyaGhosal There is a need of a testimonial page/section in the project so that the user may see past experiences of people with the website
![image](https://github.com/user-attachments/assets/7a5f3df7-72c5-4098-b36b-5f096772166c)

**Comment by 1ShahidBashir** [comment]
@PriyaGhosal Assign this issue to me , I can take care of it.
Also label with relevant labels of gssoc and hacktoberfest

**Comment by PriyaGhosal** [comment]
@1ShahidBashir Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
