### ISSUE TITLE
BUG: MAKE THIS NAVBAR TO REFLECTING EFFECT OR BLACK 

### ISSUE THREAD

**Issue by PriyaGhosal** [PriyaGhosal/BuddyTrail#1575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### DIRECTLY CREATE PR ... IT WILL BE ASSIGNED IN THIS ISSUE LATER

TEXT IS OVERLAPPING 
![image](https://github.com/user-attachments/assets/ec5dc42e-8a10-4ff8-b492-8d9e4f2daf18)
THIS WAS EARLIER ... YOU CAN ADD OLD CODE TOO OF NAVBAR
![image](https://github.com/user-attachments/assets/14cc0e86-04be-449e-a6d0-b7353e65ca6c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by RacharlaSanjana** [comment]
Hi @PriyaGhosal, I'm interested in working on this issue for Hacktoberfest . Could you please assign it to me? I'll follow the project guidelines closely.

**Comment by PriyaGhosal** [comment]
@RacharlaSanjana Yes you can work on it
