### ISSUE TITLE
Logo Change

### ISSUE THREAD

**Issue by adityakr0660** [PriyaGhosal/BuddyTrail#159]
The logo doesn't look appealing, so I need to redesign it with a more modern and attractive look.

![logo trail](https://github.com/user-attachments/assets/665854ab-6e83-41fb-909b-bbcae4af038e)

plz @PriyaGhosal assign to the task to me

**Comment by PriyaGhosal** [comment]
@adityakr0660 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow @PriyaGhosal – Project Admin on GitHub for more updates.

Happy open-source contributing! 🚀
