### ISSUE TITLE
No Alignment and Responsiveness Issue Faced

### ISSUE THREAD

**Issue by Sameeratweb** [PriyaGhosal/BuddyTrail#16]
![Screenshot 2024-10-02 063542](https://github.com/user-attachments/assets/365c87c6-8448-425d-ad80-7e325c4c5a96)
we can see things are not properly alligned and collapsing over other . Webpage needs to me responsive for small devices as well .

i would like to work on this issue. Please allow me to work on this issue and use relevant tags under GSSoC'24-Extd and Hacktober.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
