### ISSUE TITLE
" 'Navbar is static' Element Size and Make Transparent

### ISSUE THREAD

**Issue by kekubhai** [PriyaGhosal/BuddyTrail#160]
The current "Navbar is static" element is not a standard navigation element and can be confusing for users. To improve the user experience and provide a clear navigation structure, we should:

Remove the 'Navbar is static' element: Completely remove this element from the layout.
Implement a Navbar: Create a standard navbar element at the top or bottom of the page, containing links to the main sections of the website.
This change will make it easier for users to navigate through the site and find the information they are looking for.

![Screenshot 2024-10-04 153131](https://github.com/user-attachments/assets/70dacafd-7572-4950-9597-7c27f92dbb30)

Please assign me to work on the issue titled "Replace 'Navbar is static' with a Navbar Element." I have already contributed to other projects, such as GSSOC and HacktoberFest, and I believe my skills and experience would be a valuable asset to this task

**Comment by PriyaGhosal** [comment]
@kekubhai Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow @PriyaGhosal – Project Admin on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by kekubhai** [comment]
done with my owrk : 
![image](https://github.com/user-attachments/assets/3a7f225e-8929-4590-bb00-b70d57e10f4c)
also made it responsive for smaller devices. Raising a PR please Look into it.                                                                                                            Thank You
