### ISSUE TITLE
Feat:Background Color and Image Update for Exclusive Deals and Offers Page

### ISSUE THREAD

**Issue by Maanav54** [PriyaGhosal/BuddyTrail#1600]
### Describe the feature

I would like to propose a feature enhancement for the "Exclusive Deals and Offers" page. The current background color is quite dull, which does not align well with our branding and may fail to attract user attention. Additionally, I want to add background images for the prices/offers boxes.

Feature Details:

Background Color Change: Update the background color to a more vibrant option that better reflects our branding.
Location-Specific Images: Use images that are tailored to specific deals or locations, enhancing user engagement and interest.

### Add ScreenShots

![Screenshot 2024-10-26 185344](https://github.com/user-attachments/assets/14979c05-2c0e-402c-8060-d4886f01d9e4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by InderParmar** [comment]
Hi @Maanav54 ,  I am eager to work on this issue, can you please assign this issue to me?

**Comment by Maanav54** [comment]
Assign this task to @InderParmar

**Comment by InderParmar** [comment]
@Maanav54 Hi, If you can assign this issue to me, I can start working on it asap, and hopefully finish it till tomorrow.

**Comment by MansiJangid** [comment]
Hii @PriyaGhosal I have seen this issue and that page is still not looking good enough. I really want to work on it can you assign it to me please

**Comment by manastiwari99** [comment]
I  would like to work pls assign it to me
