### ISSUE TITLE
Add Contributors list 

### ISSUE THREAD

**Issue by yashksaini-coder** [PriyaGhosal/BuddyTrail#162]
@PriyaGhosal I would like to create a contributors list in the footer section of the README. My approach is to use a action workflow to retrieve & display the contibutors.

can you assign this issue to me as GSSOC contributor & add labels to it.

**Comment by PriyaGhosal** [comment]
@yashksaini-coder Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow @PriyaGhosal – Project Admin on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by yashksaini-coder** [comment]
@PriyaGhosal can you also add labels to this issue `Level 2`, `gssoc-ext`,`hacktoberfest-accepted`

**Comment by yashksaini-coder** [comment]
This issue was resolved with a new PR i raised, hence closing this issue
