### ISSUE TITLE
Add Issues & PR templates

### ISSUE THREAD

**Issue by yashksaini-coder** [PriyaGhosal/BuddyTrail#165]
@PriyaGhosal I would like to work on this enhancement, to improve your project.

Adding simple issues & PR templates can overall improve the productivity of the contributors & really help to stay informative with the work they plan to do. It will also help you identify & recognize what type of changes the contributors is planning to do in your project.

Can you assign me this issue as GSSOC contributor & add labels gssoc & hacktoberfest to it.

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.

**Comment by PriyaGhosal** [comment]
@yashksaini-coder Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow @PriyaGhosal – Project Admin on GitHub for more updates.

Happy open-source contributing! 🚀
