### ISSUE TITLE
Review page in dark mode is not working

### ISSUE THREAD

**Issue by subin-shk** [PriyaGhosal/BuddyTrail#166]
the review in dark mode does not work as intended.

![image](https://github.com/user-attachments/assets/93789da7-a244-4f73-8d1e-dfc46b58eb2f)

**Comment by PriyaGhosal** [comment]
@subin-shk Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow @PriyaGhosal – Project Admin on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by subin-shk** [comment]
also give level 3
