### ISSUE TITLE
add contributing.md file

### ISSUE THREAD

**Issue by INam1995** [PriyaGhosal/BuddyTrail#167]
Hey @PriyaGhosal 
I would like to request to be assigned the issue for adding a CONTRIBUTING.md file to BuddyTrail Project. This file will provide clear guidelines for potential contributors, enhancing our community's onboarding experience and encouraging more participation.

Here’s a brief overview of what I plan to include in the CONTRIBUTING.md file:

Project Overview
Getting Started instructions
Contributing Guidelines
Implementation steps for the search functionality enhancement
Acknowledgment of the project's Code of Conduct

so please assign this issue to me under gssoc-ext

**Comment by PriyaGhosal** [comment]
@INam1995 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow @PriyaGhosal – Project Admin on GitHub for more updates.

Happy open-source contributing! 🚀
