### ISSUE TITLE
Form creation for booking a cab or auto 

### ISSUE THREAD

**Issue by INam1995** [PriyaGhosal/BuddyTrail#169]
![image](https://github.com/user-attachments/assets/a5bbb373-9c4e-44ab-9ffd-f0fa7c427f6c)
i can make a proper form for this as it's not giving proper look to website 
so please assign it to me under gssoc - ext

**Comment by PriyaGhosal** [comment]
@INam1995 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow @PriyaGhosal – Project Admin on GitHub for more updates.

Happy open-source contributing! 🚀
