### ISSUE TITLE
Update Twitter Icon on Website

### ISSUE THREAD

**Issue by Vishwajeet594** [PriyaGhosal/BuddyTrail#17]
### Description: 
**The Twitter icon on the website is outdated, incorrect, or inconsistent with the current branding of Twitter. We need to update the icon to the latest version to ensure brand alignment and a modern appearance across the site.**

**Comment by namami-13** [comment]
I want to work on it!

**Comment by Kratika-Solanki** [comment]
@PriyaGhosal I want to work on this issue..

**Comment by 770navyasharma** [comment]
@Vishwajeet594 I want to work on this particular issue!

**Comment by PriyaGhosal** [comment]
@Vishwajeet594 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by PriyaGhosal** [comment]
@rajatsinghal02 @770navyasharma @namami-13 @Kratika-Solanki Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by Akanshaku** [comment]
If this issue is not yet resolved I would like to work on this please assign me this @PriyaGhosal
