### ISSUE TITLE
Card for reviews

### ISSUE THREAD

**Issue by INam1995** [PriyaGhosal/BuddyTrail#170]
![image](https://github.com/user-attachments/assets/c9a2d643-e350-46fe-bc04-6949f3f40a84)
i can make these reviews in card forms which will enhance our webpage 
so please assign it to me under gssoc-ext

**Comment by PriyaGhosal** [comment]
@INam1995 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow @PriyaGhosal – Project Admin on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by INam1995** [comment]
@PriyaGhosal as anyone has removed these reviews so can i add it by myself 
or would you suggest something please so that i can furthur proceed with it
