### ISSUE TITLE
Feat: add backend to the contact us form 

### ISSUE THREAD

**Issue by AyushSharma72** [PriyaGhosal/BuddyTrail#1704]
### Describe the feature

i want to add backend api and route to the contact us form in which when the user submit the form to receive an email and the information user have filled in the form 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/58fd8867-73b9-4ed1-9e23-6feacdc66395)

please assign this issue to me @PriyaGhosal under gssoc-ext and level3

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PriyaGhosal** [comment]
@AyushSharma72 Yes you can work
