### ISSUE TITLE
add explore more button content

### ISSUE THREAD

**Issue by INam1995** [PriyaGhosal/BuddyTrail#171]
![image](https://github.com/user-attachments/assets/e12eb479-e3ed-4a08-b664-fe5540d708a8)
i can make explore more button to responsive by adding info about these places in a webpage
so please assign it to me under gssoc-ext

**Comment by PriyaGhosal** [comment]
@INam1995 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow @PriyaGhosal – Project Admin on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by INam1995** [comment]
@PriyaGhosal 
is this issue has been closed ??
if yes then why because till now in deployed website this explore more button is not working
so please consider my request
![image](https://github.com/user-attachments/assets/2f49c4ff-2b74-4443-8354-e486ba8b0288)
