### ISSUE TITLE
book now is not working

### ISSUE THREAD

**Issue by INam1995** [PriyaGhosal/BuddyTrail#172]
![image](https://github.com/user-attachments/assets/761c1333-63b8-4750-855d-69cfb25653c7)
this book now is not working , i can make working by adding form so please assign it to me under gssoc - ext

**Comment by PriyaGhosal** [comment]
@INam1995 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow @PriyaGhosal – Project Admin on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by INam1995** [comment]
@PriyaGhosal please mark labels too in these issues.
