### ISSUE TITLE
Enhancement of Booking Form

### ISSUE THREAD

**Issue by neeru24** [PriyaGhosal/BuddyTrail#173]
Hey, I was looking at the booking form for cabs or autos on the website, and I think it could be improved to better match the overall UI of the site. I really appreciate the work you've done so far, and I'd love to contribute by working on this. Could you please assign me this issue? I'd be happy to get started!

![image](https://github.com/user-attachments/assets/80077b75-8cd4-4e32-8e72-363aee16e12b)

**Comment by PriyaGhosal** [comment]
@neeru24 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Level will given at the time of PR merge .Contributors  level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
