### ISSUE TITLE
Feat: Add message field to the contact form

### ISSUE THREAD

**Issue by ananyag309** [PriyaGhosal/BuddyTrail#178]
### Describe the feature

We can enhance the existing contact form by adding a message field

### Add ScreenShots

right now we can only enter name and email

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
