### ISSUE TITLE
The pop-up content does not have a direct close button.

### ISSUE THREAD

**Issue by snehhhcodes** [PriyaGhosal/BuddyTrail#18]
Hello Priya!!

I hope this message finds you well. I would like to address an issue I encountered on the website and propose a solution that I believe will enhance the user experience:

Description of the Issue:

I have noticed that the pop-up content lacks a direct close button. This can be confusing for first-time users, as they may not realize they can dismiss the pop-up by clicking anywhere outside of it.

Proposed Solution:

To improve this aspect of the user interface, I propose adding a prominent close button within the pop-up content. This button should be easily identifiable and strategically placed, allowing users to close the pop-up effortlessly. Additionally, implementing visual cues, such as hover effects, could further enhance its visibility.

If you find this proposal suitable, I would appreciate it if you could assign these tasks to me.
![Screenshot 2024-10-02 115209](https://github.com/user-attachments/assets/de774967-b029-4907-944e-210d69430991)

**Comment by rajatsinghal02** [comment]
@PriyaGhosal Please assign this issue to me! I want to solve this issue..

**Comment by PriyaGhosal** [comment]
@snehhhcodes Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
