### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by akhandpratap18** [PriyaGhosal/BuddyTrail#19]
Readme file doesnot contain steps to fork and clone the repositiory.New contributors might face this issue. I can help you update the readme file with proper guidelines and instructions. I would also make it more attractive

**Comment by akhandpratap18** [comment]
Please assign this to me

**Comment by rajatsinghal02** [comment]
@PriyaGhosal Please assign this issue to me. I want to solve this issue!

**Comment by PriyaGhosal** [comment]
@akhandpratap18 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by akhandpratap18** [comment]
Since the issue is resolved, I'll close this issue. It was great helping you guys!!.Cheers
