### ISSUE TITLE
Fixing elements in dark mode

### ISSUE THREAD

**Issue by hgjajoo** [PriyaGhosal/BuddyTrail#2]
![image](https://github.com/user-attachments/assets/bb3f0cf0-b4a8-40b7-a66a-fb5289dd6242)
Fixing the text in dark mode.

can assign me!

**Comment by Muskan-bhatt249** [comment]
@PriyaGhosal Please Assign it to me

**Comment by CHIHNITA-REDDY-B** [comment]
Please assign this issue to me aswell I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevan.

**Comment by PriyaGhosal** [comment]
@hgjajoo Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by PriyaGhosal** [comment]
@CHIHNITA-REDDY-B @Muskan-bhatt249 Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!
