### ISSUE TITLE
Font and Spacing Adjustments Needed

### ISSUE THREAD

**Issue by 770navyasharma** [PriyaGhosal/BuddyTrail#20]
I would like to report that the current font on the BuddyTrail website does not suit the overall design, affecting readability and aesthetic appeal. Additionally, the spacing between elements seems inconsistent, which detracts from the user experience. I suggest exploring alternative font options and adjusting the spacing to create a more cohesive and polished layout. Thank you for considering these improvements!
Please assign this issue to me

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
