### ISSUE TITLE
DARK MODE BUTTON NOT WORKING IN SIGN IN PAGE AND HOME LINK MISSING

### ISSUE THREAD

**Issue by 01-aniket-maity** [PriyaGhosal/BuddyTrail#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the Sign In page, the Dark Mode Button is not working. Moreover the link to navigate back to Home also seems to be missing from this page. 
I would like to fix these issues in this page.

![Screenshot 2024-10-07 195728](https://github.com/user-attachments/assets/b63e3195-7085-4d96-a56d-297dda32ac03)

@PriyaGhosal Please assign me this tasks under gssoc and hacktoberfest-accepted labels.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Raj-Aditya-27** [comment]
Hi @PriyaGhosal 
Please assign this issue to me.
I will do it within 10 minutes.
