### ISSUE TITLE
Add "FAQ" Page to the Website

### ISSUE THREAD

**Issue by SCR01** [PriyaGhosal/BuddyTrail#22]
#### Description:
We need to add an **FAQ (Frequently Asked Questions) page** to the website to address common queries and provide users with quick, accessible information about the platform.

#### Why is this important?
- An FAQ page will enhance user experience by answering common questions upfront.
- It will reduce the need for direct support for frequently asked issues, streamlining our support process.

#### Comment:
- The FAQ page should be easily accessible from the homepage, either in the header or footer.
- It should have a clear, user-friendly layout with categorized questions and answers.

**Comment by pankajsaini1** [comment]
I want to solve this issue can you please assign me

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
