### ISSUE TITLE
Change in text style for deals and itinerary sections, not very visible

### ISSUE THREAD

**Issue by Aditi2k5** [PriyaGhosal/BuddyTrail#23]
@PriyaGhosal I would like to be assigned this issue

**Comment by PriyaGhosal** [comment]
@Aditi2k5 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
