### ISSUE TITLE
Bug : Missing Hover Effect on Menu Items in Navbar

### ISSUE THREAD

**Issue by HarshadaGirase** [PriyaGhosal/BuddyTrail#25]
The menu items in the navbar currently lack a hover effect, which impacts the user experience. Adding a hover effect would provide better visual feedback and improve navigation clarity for users.

Steps to Reproduce:
Navigate to any page with the navbar.
Hover the mouse over the menu items.
Observe that there is no visual feedback (such as color change, underline, or background change) when hovering over the menu items.

Expected Behavior:
When hovering over each menu item in the navbar, there should be a visual indication such as:
Background color change
Text color change
Underline or border appearing
Any other suitable hover effect

![Screenshot (338)](https://github.com/user-attachments/assets/a31346ec-1b06-4588-a8b0-03fefda2d4f5)

**Comment by HarshadaGirase** [comment]
I would like to work on this issue kindly assign it to me ASAP.

**Comment by sambedan1** [comment]
assign this to me

**Comment by PriyaGhosal** [comment]
@HarshadaGirase Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
