### ISSUE TITLE
Bug: Missing Hover Effect on Social Icons in Footer

### ISSUE THREAD

**Issue by HarshadaGirase** [PriyaGhosal/BuddyTrail#26]
The social media icons in the footer currently do not have a hover effect, which affects the interactive experience. Adding a hover effect would provide users with visual feedback, improving the overall user experience.

Steps to Reproduce:
Scroll down to the footer on any page.
Hover over the social media icons (e.g., Facebook, Twitter, Instagram).
Observe that there is no visual change or feedback when hovering over the icons

Expected Behavior:
When hovering over a social media icon in the footer, a visual effect should be applied, such as:
Icon color change
Background color change
Scaling or animation
Any other suitable hover effect to indicate interactivity

![footer](https://github.com/user-attachments/assets/03dc70aa-1382-4bc4-85fc-2cff9b964779)

**Comment by 4F24L** [comment]
Can I work on this ? Assign me !

**Comment by foreshubham** [comment]
Assign this task to me.

**Comment by HarshadaGirase** [comment]
I would like to work on this issue kindly assign it to me ASAP.

**Comment by PriyaGhosal** [comment]
@HarshadaGirase Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by PriyaGhosal** [comment]
@4F24L @foreshubham Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!
