### ISSUE TITLE
BUG: Providing Spaces between the Text and Input Boxes in Book A Cab.

### ISSUE THREAD

**Issue by sarinsanyal** [PriyaGhosal/BuddyTrail#266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/c32a551b-e2ef-4257-9c71-0a7d721a6ccf)

Would like to implement spaces between the text and the the input boxes in the Book A Cab section.

@PriyaGhosal please assign me this issue. Also, please add Hacktoberfest and GSSoC Extended Labels. Thank you!!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vijaychandra1910** [comment]
@PriyaGhosal  please assign it to me
