### ISSUE TITLE
BUG : Text Not Clearly Visible on Location Page

### ISSUE THREAD

**Issue by HarshadaGirase** [PriyaGhosal/BuddyTrail#27]
The text on the Location page is not clearly visible against the background image, making it difficult for users to read. The issue is primarily due to the current text color blending with the background, which reduces the contrast.

Steps to Reproduce:
Navigate to the Location page.
Observe the text section (e.g., “The Perfect Travel Experience!” and the subtitle).
Notice that the text is not easily readable due to low contrast with the background.

Expected Behavior:
The text should be easily readable and stand out from the background. The font color should provide sufficient contrast against the background image.

![herosection](https://github.com/user-attachments/assets/d84a15ac-5d55-4c1b-ad9c-a83e5a48a1cf)

**Comment by PriyaGhosal** [comment]
@HarshadaGirase Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
