### ISSUE TITLE
Website Redesign Proposal 

### ISSUE THREAD

**Issue by AyushiTaralkar** [PriyaGhosal/BuddyTrail#28]
I would like to propose a comprehensive redesign of the website. After visiting your current website, I noticed areas that could be enhanced in terms of design, user experience, and functionality. A modern, visually appealing, and user-friendly website is essential in today's digital age to attract more customers and enhance their online experience.

Proposed Redesign Objectives:

**Modern and Visually Engaging Design:**
Implement a sleek, contemporary design that reflects your brand’s vibrant, fun, and high-quality offerings.
Utilize high-quality visuals of your best-selling products to entice users.

**Improved User Experience (UX):**
Redesign the website layout for easy navigation. Create clear categories for menu items, store locations, and special offers.
Enhance loading speed and performance for a seamless browsing experience.

**Incorporation of Call-to-Actions (CTAs):**
Add visible and compelling CTAs such as "Order Now," "Visit Us," and "Sign Up for Offers" to increase user engagement and drive conversions.

I’m excited to start this project and look forward to your feedback!

**Comment by Anushkam09** [comment]
I would also like to collaborate on this issue! 
Some redesigning ideas I have: 
1. Make the font, color, text size uniform throughout.
2. Improve the cards, add pictures
3. Change the contact us, submit review and 'what others are saying' section

Website could use some redesigning of these sections: 
![image](https://github.com/user-attachments/assets/9fd5c015-9bf5-4afc-ac4f-cef6213342f9)
![image](https://github.com/user-attachments/assets/1d1cc7fb-912b-483c-b1f8-d1eb5fb2755a)
![image](https://github.com/user-attachments/assets/fa142328-9a25-4f26-9f00-3b0b07a1b24e)

**Comment by PriyaGhosal** [comment]
@Anushkam09 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by PriyaGhosal** [comment]
@Anushkam09 If @AyushiTaralkar has no problem with it then you both can collaborate

**Comment by AyushiTaralkar** [comment]
thank you for assigning me this task. Sure i would love to collaborate .

**Comment by Anushkam09** [comment]
Thank you so much @AyushiTaralkar for collaborating. @PriyaGhosal can you please assign me too?

**Comment by AyushiTaralkar** [comment]
I made the new landing page for your website pls tell if you like it so that i can work on further pages also @PriyaGhosal 
![Screenshot 2024-10-05 142250](https://github.com/user-attachments/assets/5d0032e1-0e55-46fd-8231-9986fd0939f4)

**Comment by AyushiTaralkar** [comment]
please feel free to inform me if you want any changes... @PriyaGhosal
