### ISSUE TITLE
Redirect to home page on clicking logo

### ISSUE THREAD

**Issue by Abankita** [PriyaGhosal/BuddyTrail#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the code change

On clicking the logo, it will be better if the website redirects to the home page, when present in a different page. 

### Proposed solution

I'll write the link of the home page in the logo code. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Rashigera** [comment]
Could this be assigned to me
