### ISSUE TITLE
CODE CHANGE: Improve UI of Book a Cab or Auto

### ISSUE THREAD

**Issue by Anjalee01** [PriyaGhosal/BuddyTrail#288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the code change

@PriyaGhosal  @dwivedishrey @samarth-6

Current UI of looks like this, I want to iprove it 

![image](https://github.com/user-attachments/assets/d7de0ccc-fd79-435d-b82e-25c16eaadc11)

### Proposed solution

I will align input box and add styling so it looks visually appealing.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Karnmayank07** [comment]
Hi @PriyaGhosal 

I already submitted a PR for this issue, and you closed it due to conflicts. The issue number is #155, but there is still no solution implemented on the website. Moreover, more contributors are raising this same issue. Please look into this matter 🙂🙂

**Comment by sarinsanyal** [comment]
I actually opened the issue myself, and successfully submitted a PR in this. Kindly check into this matter. @Karnmayank07 @Anjalee01 

My Issue: #266 
My Successful PR: #273
