### ISSUE TITLE
Exclusive deals dailog Box and navbar responsiveness

### ISSUE THREAD

**Issue by itsbhh** [PriyaGhosal/BuddyTrail#29]
Could you please assign this issue to me under GSSOC'24 extd and Hacktoberfest? I would like to work on making the navbar more user-friendly and responsve and implement it as sidebar and also wanna change the button implementation on exclusive deals dialog box. Thanks!
![image](https://github.com/user-attachments/assets/2769a743-8fa3-4568-8e8e-de8da685248d)
![image](https://github.com/user-attachments/assets/0ce8c8a7-b3aa-4d15-8adc-991f1f3904a8)

**Comment by PriyaGhosal** [comment]
@itsbhh Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
