### ISSUE TITLE
Dark/Light Mode Toggle Button Misaligned in Navbar - Not Centered Vertically

### ISSUE THREAD

**Issue by Hamza20203064** [PriyaGhosal/BuddyTrail#3]
The dark/light mode toggle button in the website's navbar is not vertically centered. This causes a visual misalignment, affecting the overall layout of the navbar. The button should be adjusted to ensure it is centrally aligned from the top to match the rest of the navbar elements for a consistent and polished appearance. This issue persists across all screen sizes
![Screenshot 2024-10-01 175407](https://github.com/user-attachments/assets/e0ac4673-c73a-49fe-84ea-fe03d1be5e39)
If you assigned to me underGSSoC'24- Extd., I would like to fix it.

**Comment by foreshubham** [comment]
Hello, please assign this task to me. I can do this very efficiently and please mark this as hacktoberfest, gssoc, and gssoc-extd

**Comment by PriyaGhosal** [comment]
@foreshubham Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by PriyaGhosal** [comment]
@Hamza20203064 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
