### ISSUE TITLE
BUG: Improving Sign - In Page.

### ISSUE THREAD

**Issue by sarinsanyal** [PriyaGhosal/BuddyTrail#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/61ca3ca3-9437-4898-8179-95225b1d2844)

The Navbar in the sign-in page doesn't have clear looking titles, and the grey is getting mixed with the background white. Would like to implement the changes. Also, would like to implement a `margin-bottom:30px` under the Sign In div. 

@PriyaGhosal kindly assign me this issue. Also, please add the GSSoC Extended and Hacktoberfest labels please. Thank you!!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by poorvikaa08** [comment]
This issue is already assigned to me

**Comment by poorvikaa08** [comment]
@sarinsanyal 
Work on other issues

**Comment by sarinsanyal** [comment]
@poorvikaa08 I just checked the message right now. I have submitted a PR. Should I revert it back?

**Comment by poorvikaa08** [comment]
> @poorvikaa08 I just checked the message right now. I am really sorry. I have submitted a PR. Should I revert it back?

@sarinsanyal 
Sorry but yeah, since it was assigned to me earlier

**Comment by sarinsanyal** [comment]
> > @poorvikaa08 I just checked the message right now. I am really sorry. I have submitted a PR. Should I revert it back?
> 
> @sarinsanyal Sorry but yeah, since it was assigned to me earlier

Is there anyway I can help? @poorvikaa08

**Comment by poorvikaa08** [comment]
@sarinsanyal 
It's the git bot that assigns

**Comment by poorvikaa08** [comment]
PA has to assign members for the issue

**Comment by souvikpramanikgit** [comment]
Assign me this issue
