### ISSUE TITLE
DOC: Modification of README.md file(Design), & Creation of dedicated Contributing.md file and LICENSE.

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [PriyaGhosal/BuddyTrail#311]
### 1) Add animated line separators

This will make the **README.md** file look more attractive and engaging for the Users and Contributors

### 2) Modifiy the **Contributors section**.
I noticed that you are manually adding the contributors to your project. I want to try and automate the process to reduce your workload. 
**NOTE:** However, let me mention that the looks will change(screenshot attached below).

### 3) Add a **Team section**
This will help the Contributors know about the Project Admin and who to contact if they face any issues. 

## 2. Add a dedicated Contributing.md
A dedicated file for contributors to refer to and understand where to begin with. Merging the README.md with the Contributing section reflects poor documentation style. I will provide a brief idea about the contribution in the **README.md** file and provide a redirect to the newly made **Contributing.md** file for contributors to refer to.
I would also add a redirect to **Contributing.md** from **README.md**

## 3. Add MIT LICENSE
The presence of a **LICENSE** file explicitly states the terms under which the code can be used, modified, and shared. If a project does not have a **LICENSE** file, it implies that the author has not granted any rights to others, and legally, no one has permission to use, distribute, or modify the code.
So, adding a LICENSE file is a best practice for open-source projects.

I would like to work on the issues so that I can contribute to making the repository more accessible and friendly for other Contributors.
Please assign this issue to me under level3, gssoc-ext and hacktoberfest-accepted(if available) labels.

### 1) Add animated line separators

![image](https://github.com/user-attachments/assets/4dd78a96-9066-4614-bba6-58dd654c3bf7)

### 2) Modifiy the **Contributors section**.

- Before

This is taking up a lot of space and resulting in unnecessary scrolling in the **README.md** file.
![image](https://github.com/user-attachments/assets/2b5f856a-72d6-4701-8c06-f1409891b2e1)

- After

This will give a neat outlook and also enhance the readability of the README.md file.
![image](https://github.com/user-attachments/assets/1ec1e50b-fcab-4b4f-8289-8627f108c540)

### 3) Add a **Team section**

![image](https://github.com/user-attachments/assets/fae867de-c89c-441c-82ba-4b0d6374ef39)

## 2. Add a dedicated Contributing.md

Reference file image:
![image](https://github.com/user-attachments/assets/274556d1-6f47-43eb-9e22-a0b6986f3c8f)
![image](https://github.com/user-attachments/assets/c59801df-632e-4966-b05d-e36c0234e338)
![image](https://github.com/user-attachments/assets/dd772221-db42-416c-8398-389677255c63)

## 3. Add MIT LICENSE

![image](https://github.com/user-attachments/assets/17e527af-96ab-4a68-925d-1e417a38e636)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by rajdeepchakraborty-rc** [comment]
@PriyaGhosal I also noticed while working that you don't have a LICENSE for your project. Do you want me to add it to my issue and work on it?

**Comment by rajdeepchakraborty-rc** [comment]
@PriyaGhosal Please do let me know.

**Comment by rajdeepchakraborty-rc** [comment]
@PriyaGhosal wanted to update you regarding the work. I have successfully automated the process of adding the contributors in your README.md file. You no more have to manually add the Contributors(reflecting poor documentation practice). 
![image](https://github.com/user-attachments/assets/ec156f18-9613-424d-91c5-ae185c762ffb)

**Comment by rajdeepchakraborty-rc** [comment]
> @PriyaGhosal wanted to update you regarding the work. I have successfully automated the process of adding the contributors in your README.md file. You no more have to manually add the Contributors(reflecting poor documentation practice). ![image](https://private-user-images.githubusercontent.com/68934988/374930889-ec156f18-9613-424d-91c5-ae185c762ffb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NzI0ODQsIm5iZiI6MTcyODQ3MjE4NCwicGF0aCI6Ii82ODkzNDk4OC8zNzQ5MzA4ODktZWMxNTZmMTgtOTYxMy00MjRkLTkxYzUtYWUxODVjNzYyZmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDExMDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5MzFiN2ViNzQ1NTRkOTcxMmM1MmQwZDgyZGI5MjA5ZjBhNTUyY2M1YmQ5MWVlYTMxNzc4MWYxZjdlNDJiNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JW4XeFGwTvjukQgpu2nGqejobaww1NlTd0rxuaSrK6k)

This will update automatically!

**Comment by rajdeepchakraborty-rc** [comment]
> @PriyaGhosal I also noticed while working that you don't have a LICENSE for your project. Do you want me to add it to my issue and work on it since I am working on updating the documentation of the project? Since this is an open-source project, it should have a LICENSE in it.

@PriyaGhosal Please update me regarding this so that I can either add it and open a PR.

**Comment by PriyaGhosal** [comment]
@rajdeepchakraborty-rc Sorry for the inconvenience caused You can surely add license .. Create new pr I will surely merge it

**Comment by rajdeepchakraborty-rc** [comment]
@PriyaGhosal I have not yet created the PR was waiting for you response

**Comment by rajdeepchakraborty-rc** [comment]
I am done with most of the work. Just adding the LICENSE is left. Will add that and open a PR and let you know.

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc Sorry for the inconvenience caused You can surely add license .. Create new pr I will surely merge it ......You have done great job :)

Thanks for the appreciation.

**Comment by PriyaGhosal** [comment]
@rajdeepchakraborty-rc You need not to ask me .... Any contributor is free to raise issue and create PR ..... Thank You for your Patience

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc You need not to ask me .... Any contributor is free to raise issue and create PR ..... Thank You for your Patience

Please try to visit the issues once in a while as Contributors might wanna ask you doubts or share and feedback with you.

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc You need not to ask me .... Any contributor is free to raise issue and create PR ..... Thank You for your Patience

Since I am working in your project, I must ethically let you know about any changes I am making. I was just doing that. Thanks for your reply.

**Comment by rajdeepchakraborty-rc** [comment]
@PriyaGhosal Please let me know once you are done merging because I am constantly getting conflicts. I will resolve the conflicts once you are done merging PRs.

**Comment by rajdeepchakraborty-rc** [comment]
Also Please do not add Contributors manually anymore. I don't know who is adding them. Please tell that person to stop as I have automated the process.

**Comment by rajdeepchakraborty-rc** [comment]
@PriyaGhosal Please update the level to **level2**
