### ISSUE TITLE
Dark mode implementation for your cool website

### ISSUE THREAD

**Issue by STDYGIT** [PriyaGhosal/BuddyTrail#34]
HEY @PriyaGhosal 
![Screenshot 2024-10-02 at 12 44 47 PM](https://github.com/user-attachments/assets/b2ba4824-6f30-4ea5-b24a-fee5078992fb)
![Screenshot 2024-10-02 at 12 44 31 PM](https://github.com/user-attachments/assets/820f1dd4-992a-496f-ad3e-45169e01bd52)
 it will be so cool to make your website in dark theme too with these cool switch

**Comment by STDYGIT** [comment]
Mam, I would like to work on this feature and would appreciate it if you could assign it to me for Hacktoberfest and GGSOC '24. I believe this is a level 2 task / level 3 task, as it requires a complete overhaul of the page styles. Thank you!

**Comment by PriyaGhosal** [comment]
@STDYGIT Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by STDYGIT** [comment]
Mam it needs at least level 2 as the whole site needs a theme changer
