### ISSUE TITLE
FIXING RESPONSIVE ISSUE

### ISSUE THREAD

**Issue by Archisman141** [PriyaGhosal/BuddyTrail#35]
![Screenshot_20241003_161718_Chrome.jpg](https://github.com/user-attachments/assets/85beb1a0-1761-4194-824f-940a3d9abf1c)

![Screenshot_20241003_161731_Chrome.jpg](https://github.com/user-attachments/assets/196a1366-1d07-4b8a-a57c-aabfb0780f14)

The website responsiveness is not up to the mark and show various issues. I want to fix these issues. 

Also the color of text in the box in dark theme is of low visibility, I want to fix this issue

Please assign me this work and also add gssoc-extd label, hacktoberfest-accepted label.

**Comment by PriyaGhosal** [comment]
@Archisman141 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

**Comment by Pragyaa3** [comment]
Hello @PriyaGhosal , I would also like to work on this issue.

**Comment by Archisman141** [comment]
@PriyaGhosal The issue is fixed, please check it

**Comment by Archisman141** [comment]
@PriyaGhosal The issue is resolved
....Please check it and merge it.
