### ISSUE TITLE
BUG: NO PROPER ALLIGNMENT OF NAV BAR

### ISSUE THREAD

**Issue by HS202022** [PriyaGhosal/BuddyTrail#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-10-09 121813](https://github.com/user-attachments/assets/912597da-7b91-4c5b-bc87-14bc1fc8c85e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Nimit1775** [comment]
hey  @HS202022  i have fixed this in  PR #355  kindly check the updated site
