### ISSUE TITLE
BUG:Fix The Website With Old Code

### ISSUE THREAD

**Issue by PriyaGhosal** [PriyaGhosal/BuddyTrail#375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### **Direct create Pull Request I will assign you in issue later**

**Remove** the code and make it look like **before** as overlapping is done 

 BEFORE:
![image](https://github.com/user-attachments/assets/25069db6-7371-4a2b-a031-d365edf37d84)
![image](https://github.com/user-attachments/assets/3c6b8e47-4375-4e85-a399-8b456d9d7789)
 
NOW :
![image](https://github.com/user-attachments/assets/e144897d-6344-429e-999f-440c6367322f)
![image](https://github.com/user-attachments/assets/20172a61-06c3-4bb0-b0b9-faf8b8d1d958)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Nimit1775** [comment]
@PriyaGhosal  the header   overlapping issue was fixed in PR #355 and merged

**Comment by Son7c** [comment]
@PriyaGhosal assign me this as you requested

**Comment by souvikpramanikgit** [comment]
Assign me this issue i will do it
