### ISSUE TITLE
update footer

### ISSUE THREAD

**Issue by abhi200446** [PriyaGhosal/BuddyTrail#386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the code change

the footer section is not properly arranged please assign me @pr
![image](https://github.com/user-attachments/assets/767e7dc7-113c-48a5-8548-b03a64e4f17e)

### Proposed solution

i enhance the footer section which looks clean and clear

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RoshanKumar9421** [comment]
can i work on this
