### ISSUE TITLE
Improve Text Visibility in Dark Mode for Enhanced Readability

### ISSUE THREAD

**Issue by Hamza20203064** [PriyaGhosal/BuddyTrail#4]
Texts are not visible in dark mode.
![Screenshot 2024-10-01 175854](https://github.com/user-attachments/assets/4f252cdd-e23a-47fe-8635-b00cf9e396b7)
![Screenshot 2024-10-01 175848](https://github.com/user-attachments/assets/5ce64eb7-6f38-473f-8690-92cbb9b8ba64)
![Screenshot 2024-10-01 175831](https://github.com/user-attachments/assets/5c70dde8-1844-4852-ba99-fb77eff32f6f)
![Screenshot 2024-10-01 175757](https://github.com/user-attachments/assets/39194f30-5bc2-4b0c-ae29-927a4a7c35c8)
![Screenshot 2024-10-01 175749](https://github.com/user-attachments/assets/6d40d12e-b6de-4e42-9b15-12ebe7590f38)

**Comment by Thanmai44** [comment]
Assign this issue to me. I am interested in working on this project.

**Comment by Hamza20203064** [comment]
@PriyaGhosal Please assign this issue to me under gssoc'24-extd. I would like to work on it.

**Comment by CodingGirlGargi** [comment]
@PriyaGhosal kindly assign me this for gssoc24 extd. I am interested to work on it.

**Comment by PriyaGhosal** [comment]
@Hamza20203064 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by PriyaGhosal** [comment]
@Thanmai44 @CodingGirlGargi Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!
