### ISSUE TITLE
Enhancement of Contact Us Page

### ISSUE THREAD

**Issue by Abhiraj-Sardar** [PriyaGhosal/BuddyTrail#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the code change

Hi @PriyaGhosal ,

The Contact Us Page UI Seems not good , The text are not properly visible. In both Light and Dark Mode. 
I want to upgrade the UI and also want to work on this issue .

please assign this task to me. and please add **gssoc-ext** , **level1**,**level2** etc labels.

Thank You

![{EB608249-58E9-4CA9-BE50-96347135937A}](https://github.com/user-attachments/assets/91dcdbda-655c-4d7b-a73b-a9fd11262401)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ShradhaSaxena23** [comment]
I want to work on this issue please assign me .

**Comment by AnshuWorld** [comment]
Please assign me this task under gssoc24 extd
