### ISSUE TITLE
CODE CHANGE:  Contact us page is twice in the website. 

### ISSUE THREAD

**Issue by Kajalmehta29** [PriyaGhosal/BuddyTrail#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the code change

i want to fix the issue of duplication of contact us page.
Please assign this issue to me under gssoc-extd and hacktoberfest.

### Proposed solution

I will remove one contact us page and fix the portal.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harshbhar0629** [comment]
Can i fix that issue??
