### ISSUE TITLE
Text not visible clearly in dark mode

### ISSUE THREAD

**Issue by ankiiitagupta** [PriyaGhosal/BuddyTrail#43]
In dark mode, the text in review section is not clearly visible and also not according to the dark mode

![Screenshot 2024-10-03 180226](https://github.com/user-attachments/assets/a411578e-b339-40b7-9245-7e02fa8cfb53)

Kindly assign this task to me under GSSOC extd'24.

**Comment by PriyaGhosal** [comment]
@ankiiitagupta Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
