### ISSUE TITLE
Missing Contributing.md file

### ISSUE THREAD

**Issue by archanasingh11** [PriyaGhosal/BuddyTrail#45]
**Description:**

The `CONTRIBUTING.md` file is missing from the BuddyTrail repository. This file is essential for guiding new contributors through the process of setting up the project, adhering to coding standards, and submitting pull requests. Without it, contributors may lack clarity on how to effectively contribute to the project, which could lead to inconsistencies and confusion.

I recommend adding a `CONTRIBUTING.md` file to outline:
- Steps for setting up the repository locally.
- Branching and submission of pull requests.
- Code style guidelines and best practices.
- How to report issues and propose new features.

Please @PriyaGhosal  assign me this task with label "GSSOC-Ext", "Hacktoberfest-accepted" and "level1".

**Comment by PriyaGhosal** [comment]
@archanasingh11 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
