### ISSUE TITLE
Scroll to top

### ISSUE THREAD

**Issue by archanasingh11** [PriyaGhosal/BuddyTrail#47]
**Description**: 
The website currently lacks a "Scroll to Top" feature, which is essential for enhancing user experience. This feature would allow users to easily return to the top of the page after scrolling down through content-heavy sections.

**Steps to Reproduce** (for a bug):
1. Open the website on any browser.
2. Scroll down to the bottom of the page.
3. Observe that there is no "Scroll to Top" button or functionality available.
   
**Expected Behavior**:
A button (or another UI element) should appear when the user scrolls down a significant portion of the page. Clicking this button should smoothly scroll the user back to the top of the page.

**Actual Behavior**:
No such button appears, and the user must manually scroll back to the top.

**Possible Solution**:
Implement a "Scroll to Top" button that becomes visible after the user has scrolled down a certain distance from the top. The button should have the following behavior:
- **Visibility**: Appears when the user scrolls down 50% of the viewport height or more.
- **Click Action**: When clicked, the page smoothly scrolls to the top.
- **Design**: A minimalistic arrow icon, positioned at the bottom-right of the page.

Please @PriyaGhosal assign me this task with labels "GSSOC-Ext", "Hacktoberfest-accepted" and "level1".

**Comment by Shivang-v-erm-a** [comment]
can you please assign it to me

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
