### ISSUE TITLE
Updation of footer

### ISSUE THREAD

**Issue by Madan2468** [PriyaGhosal/BuddyTrail#48]
Footer can be updated by adding animations, making ui more beautiful, adding hover effects and adding copyright line for professional look. 

<img width="1253" alt="Screenshot 2024-09-29 at 11 07 03 PM" src="https://github.com/user-attachments/assets/2aa7f133-19ca-462b-aec7-86a654e5e509">

So kindly assign me this under hacktoberfest 2024

**Comment by Krishnamverma951** [comment]
![Screenshot 2024-10-03 235733](https://github.com/user-attachments/assets/308e975c-4063-42b0-9afe-19fa6f3191ec)
i have already use in my website

please assign me this issue

**Comment by Neha0303-debug** [comment]
please assign this to me to make the footer section more beautiful.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by Neha0303-debug** [comment]
@PriyaGhosal I have got mail but I am confused that the issue has been assigned to me or @Madan2468. Please let me clear this.

**Comment by PriyaGhosal** [comment]
@Neha0303-debug issues are assigned on first come first serve basis but if any contributor fails to do so in one week then you can do it by simply tagging me here and I will assign it to you
