### ISSUE TITLE
Feat: Improvements Needed for the Contact Us Page

### ISSUE THREAD

**Issue by yasheela-alla** [PriyaGhosal/BuddyTrail#489]
### Describe the feature

**Description:**

The current "Contact Us" page of the BuddyTrail website has a clean layout but lacks several elements that could enhance user experience and engagement.

#### **Input Fields:**
   - The input fields for the Name and Email do not have labels, making it unclear to users what information is required. Adding descriptive labels above each field would enhance clarity.
   - like adding placeholder text in the input fields (e.g., "Enter your name", "Enter your email") for better guidance.

#### Proposed Solution:

  
- **Label Addition:**
   include `<label>` tags for the input fields.

@PriyaGhosal I'd like to work on this issue, Please assign me! Thank you :)

### Add ScreenShots

![image](https://github.com/user-attachments/assets/78b7fc16-e8f6-42d8-82d7-9e9161d2f420)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shambhavipathak24** [comment]
I would like to work on contact us page .Please assign this to me._
