### ISSUE TITLE
[Bug] The Pop-Up issue

### ISSUE THREAD

**Issue by Jazz-45** [PriyaGhosal/BuddyTrail#49]
The pop-up never goes back after the clicking . 
There should be a cut button on the top right to cancel if not needed.
This bug hinders the smooth user experience of the website.
I will solve the issue of this pop-up also will also change the way how it looks by changing the font and writing a better and exciting prompt. Please assign this issue to me under the : 
1. gssoc-ext tag
2. hacktoberfest tag
3. Level -3 ( As it a issue that solves a bug and also enhances the website ).
![Screenshot 2024-10-03 193313](https://github.com/user-attachments/assets/3277632e-0f83-40e9-aaed-a0ed17a10db0)

**Comment by HarshAgrawal1** [comment]
Can i work on this issue?

**Comment by PriyaGhosal** [comment]
@HarshAgrawal1 @Jazz-45 This issue already exists. Please check the existing issues before raising a new one. Find another issue or feature to contribute to. Thank you!
