### ISSUE TITLE
Cards Not Visible in Dark Mode

### ISSUE THREAD

**Issue by Hamza20203064** [PriyaGhosal/BuddyTrail#5]
When using dark mode, some cards on the page may not be visible due to insufficient contrast between the background and text colors. 
Light mode:
![Screenshot 2024-10-01 181041](https://github.com/user-attachments/assets/4c70b7ea-df26-46c5-8b03-916fbd50654e)
Dark mode:
![Screenshot 2024-10-01 181056](https://github.com/user-attachments/assets/72efaed3-b0d5-44ce-85e2-1bc15fcbfbdf)

**Comment by icemberg** [comment]
can you assign this issue to me?

**Comment by icemberg** [comment]
I would be happy to solve this problem

**Comment by Hamza20203064** [comment]
If you assign this issue under GSSoC'24-extd, then I would love to work on that.

**Comment by PriyaGhosal** [comment]
@icemberg Issues are assigned on a first-come, first-served basis. If a contributor doesn't contribute within 1 week, it will be reassigned to the next person who requested it. You can wait or find another bug/feature to contribute to. Thank you!

**Comment by PriyaGhosal** [comment]
@Hamza20203064 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
