### ISSUE TITLE
Update Twitter Icon to New X Logo

### ISSUE THREAD

**Issue by sriharsha0x1** [PriyaGhosal/BuddyTrail#50]
![image](https://github.com/user-attachments/assets/c0215460-b477-49df-9453-fc2a72fde210)
@PriyaGhosal 
will replace the current Twitter bird icon with the new X icon across the website. The new icon should be aligned and styled consistently with the other social media icons (Instagram and YouTube). Please assign this task to me for implementation.

**Comment by PriyaGhosal** [comment]
@sriharsha0x1 Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
