### ISSUE TITLE
Add mini chartbot to the website.

### ISSUE THREAD

**Issue by ruchikakengal** [PriyaGhosal/BuddyTrail#51]
it gives Answers of users questons and give fast resoonse to the users

**Comment by dwivedishrey** [comment]
@ruchikakengal I’ve assigned this issue to you. Please go ahead and start working on it.

**Comment by jyothimanoj12** [comment]
can you assign this issue to me

**Comment by PriyaGhosal** [comment]
@ruchikakengal Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
