### ISSUE TITLE
Adding hover effect to the topics in the header to let users know where they are navigating.

### ISSUE THREAD

**Issue by Akshithanaverse** [PriyaGhosal/BuddyTrail#52]
![Screenshot 2024-10-03 203407](https://github.com/user-attachments/assets/8c4a88d4-ee45-4994-b959-1f02ecfdf583)
->Hover is not present which might lead to ambiguity.

**Comment by PriyaGhosal** [comment]
@Akshithanaverse Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
