### ISSUE TITLE
Enhancing "User Reviews and ratings" Section

### ISSUE THREAD

**Issue by Bhum-ika** [PriyaGhosal/BuddyTrail#55]
Proper spacing is required above the form.
The font size can be changed to make the difference between different information written.
The UI can be enhanced further in terms of the rating part.

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by Bhum-ika** [comment]
@PriyaGhosal Kindly check your discord profile
