### ISSUE TITLE
BUG: After submitting the review, the text message box is not clearly visible 

### ISSUE THREAD

**Issue by laxmikandivalasa** [PriyaGhosal/BuddyTrail#558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot (268)](https://github.com/user-attachments/assets/67468a40-1119-4fde-91dc-44201746fe1f)
i've submitted a review this is how the message prompted
I'd like to change the text color and msg prompted after submit.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...

**Comment by laxmikandivalasa** [comment]
can you review the pr #561
