### ISSUE TITLE
Expanding travel package pages

### ISSUE THREAD

**Issue by rees8** [PriyaGhosal/BuddyTrail#57]
Under the "Exclusive Deals and Offers" section, the packages are listed with a one-line explanation and a "Book Now " button.
We could add button functionalities in the .js file to redirect to a new page for each of the packages.
This page will explain in detail about the package so that the user can make a decision whether to go ahead with the purchase or not.
Each package would have a separate index and style page for this purpose.
If this sounds good, I would like to work on this @PriyaGhosal

**Comment by Krishnamverma951** [comment]
I want to work on this issue 
 please assign me.

**Comment by rees8** [comment]
@Krishnamverma951 I am also a contributor, these are contributor-raised issues. I've already raised the issue and asked the project lead to assign this to me. Meanwhile, you can look into other issues or raise one yourself. Hope this helps.

**Comment by PriyaGhosal** [comment]
@rees8 Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
