### ISSUE TITLE
Navbar background 

### ISSUE THREAD

**Issue by Sarthakkashyapp** [PriyaGhosal/BuddyTrail#570]
### Describe the feature

Navbar should have a proper dedicated background on scrolling it looks odd.

### Add ScreenShots

![Screenshot_2024-10-12-18-53-45-81_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/d4ce220a-ed61-4dae-8661-71ff682975ec)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...

**Comment by Sarthakkashyapp** [comment]
@SaanyaGarg5 I am already working on this
