### ISSUE TITLE
BUG: LOGO NOT RESPONSIVE AND DARK MODE ISNT WORKING IN BOOK CAB AND TEXT NOT VISIBLE 

### ISSUE THREAD

**Issue by HS202022** [PriyaGhosal/BuddyTrail#571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

LOGO IS NOT RESPONSIVE IT SHOULD REFRESH OR RELOAD THE WEBPAGE AND THE BOOK CAB SECTION DOESNT CHANGE THE COLOR IN DARK MODE AND TEXT INVISIBILITY

https://github.com/user-attachments/assets/b009df15-6042-45a4-9e28-f47ddfa221c2

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ayesha480** [comment]
Cam I try this?
