### ISSUE TITLE
Improving footer design

### ISSUE THREAD

**Issue by Palmistry2310** [PriyaGhosal/BuddyTrail#572]
the current footer is to big, i would really like to improve its design and enhance it with animation and hover effects.
the current footer:
![Screenshot 2024-10-12 195535](https://github.com/user-attachments/assets/86f74f6d-398a-40b4-b7bc-343b43ee3ed7)

@PriyaGhosal can u please assign me this issue under gssoc-ext, hacktoberfest-accepted and level label?

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...
