### ISSUE TITLE
BUG: Login Signup Form Validation with custom toasts

### ISSUE THREAD

**Issue by tarunkumar2005** [PriyaGhosal/BuddyTrail#578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/52c51cd4-e3eb-4c15-aa34-a7c1e26d0662)

@PriyaGhosal Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...
