### ISSUE TITLE
Responsive Navbar For Smaller Screens

### ISSUE THREAD

**Issue by Bhanuprakash842** [PriyaGhosal/BuddyTrail#58]
In the Mobile Screens I want to add the Three Bars icon to make the nav bar Responsive .Whenever the User clicks on the Horizontal Bars Icon then the div will dropdown with all the nav items.
![image](https://github.com/user-attachments/assets/dcfd271f-0d14-44a2-9fd5-bbd9232b7503)
The Above Image is just to show my idea .I can Beautify it more according to our color palette.
I Would be grateful if you assign me this issue under **Gssoc-ext,hactoberfest** . My Github Username is @Bhanuprakash842

**Comment by PriyaGhosal** [comment]
@Bhanuprakash842 Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
