### ISSUE TITLE
Hover on nav bar 

### ISSUE THREAD

**Issue by rohir1132yadav** [PriyaGhosal/BuddyTrail#59]
Hove on navbar like location review etc. and also change color on hover.

**Comment by rohir1132yadav** [comment]
I want to work on this issue #59 . please assign me.

**Comment by vijay1172** [comment]
I want to work on this issue #59 please assign me.

**Comment by PriyaGhosal** [comment]
@rohir1132yadav Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
