### ISSUE TITLE
change of navbar according to theme 

### ISSUE THREAD

**Issue by kashishchadha** [PriyaGhosal/BuddyTrail#60]
as in dark mode nav is not going with the  theme i can make it better for u please assign me this i will make itbetter

**Comment by PriyaGhosal** [comment]
@kashishchadha Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by vijaychandra1910** [comment]
@PriyaGhosal please assign it to me .
