### ISSUE TITLE
navigation bar underline hover effect 

### ISSUE THREAD

**Issue by Krishnamverma951** [PriyaGhosal/BuddyTrail#61]
https://github.com/user-attachments/assets/6cf9e598-5be1-4787-9cce-3e86c3e15bc0

i have use in my website

in the navbar do not have hover effects, making them feel less interactive. I can add smooth hover transitions
Please assign this issue to me under gssoc'24 EXTENDED with label gssoc'24

**Comment by PriyaGhosal** [comment]
@Krishnamverma951 Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by Krishnamverma951** [comment]
Hi please  mam hactoberfrst tag  removed

**Comment by Krishnamverma951** [comment]
Thanks  for  giving me
