### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by shreyad2806** [PriyaGhosal/BuddyTrail#63]
I can add a personalized logo to make it look more professional and asthetic.
Please assign me under gssoc and hactoberfest.

**Comment by PriyaGhosal** [comment]
@shreyad2806 Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
