### ISSUE TITLE
BUG: FIX NAVBAR

### ISSUE THREAD

**Issue by PriyaGhosal** [PriyaGhosal/BuddyTrail#678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### DIRECTLY CREATE PR ... IT WILL BE ASSIGNED IN THIS ISSUE LATER
![image](https://github.com/user-attachments/assets/8feef248-11ef-421f-8d78-2297ee7c740f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Sudhanshu248** [comment]
@PriyaGhosal Kindly assign me this issue under the label of Hacktoberfest'24, hacktoberfest-accepted, level-2.

I can remove it.
