### ISSUE TITLE
BUG: REMOVE THIS PICTURE 

### ISSUE THREAD

**Issue by PriyaGhosal** [PriyaGhosal/BuddyTrail#679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### DIRECTLY CREATE PR ... IT WILL BE ASSIGNED IN THIS ISSUE LATER

![image](https://github.com/user-attachments/assets/76d33bb6-b891-4c90-9d18-4b10348dbe0a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Sudhanshu248** [comment]
@PriyaGhosal Kindly assign me this issue under the label of Hacktoberfest'24, hacktoberfest-accepted, level-2.

I can remove it.
