### ISSUE TITLE
Feat: DARK MODE TO THE WEBSITE 

### ISSUE THREAD

**Issue by PriyaGhosal** [PriyaGhosal/BuddyTrail#680]
### DIRECTLY CREATE PR ... IT WILL BE ASSIGNED IN THIS ISSUE LATER
ADD MOON FOR DARK MODE

### Add ScreenShots

![image](https://github.com/user-attachments/assets/9ca6bff6-6657-4770-848e-f99b0334fb8c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by OmmDevgoswami** [comment]
Can you please assign this to me.
