### ISSUE TITLE
Beautify the Footer.

### ISSUE THREAD

**Issue by Bhanuprakash842** [PriyaGhosal/BuddyTrail#7]
I want to add the copyright in the footer,change the twitter icon to X icon and beautify the footer with all the required information.
![Screenshot 2024-10-01 211504](https://github.com/user-attachments/assets/5f5e677e-7e9c-4833-9c6f-70f0444c6433)
I would be grateful if you assign me this task under the label Gssoc-ext,Hacktoberfest .My github username is @Bhanuprakash842

**Comment by PriyaGhosal** [comment]
@Bhanuprakash842 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
