### ISSUE TITLE
Update Styling of Website including font and spacing

### ISSUE THREAD

**Issue by 770navyasharma** [PriyaGhosal/BuddyTrail#70]
I Want to update the style of the CSS

OLD Version
<img width="1442" alt="Screenshot 2024-10-04 at 3 33 08 PM" src="https://github.com/user-attachments/assets/04944ce6-0183-4682-a638-11c2c28b76f7">

I have made some changes assign this issue to me so that I will commit and open the pull request.

<img width="1442" alt="Screenshot 2024-10-04 at 3 31 50 PM" src="https://github.com/user-attachments/assets/df828bae-c2d1-4af5-82d9-3ce9ca5b29f7">

@PriyaGhosal Please assign this issue to me.

**Comment by PriyaGhosal** [comment]
@770navyasharma Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
