### ISSUE TITLE
CODE CHANGE: fixing the shape of buttons of carousel section and fixing button size of booking section form alongside its heading color

### ISSUE THREAD

**Issue by justanayush** [PriyaGhosal/BuddyTrail#701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the code change

the shape of buttons on carousel to slide to next card isnt circular and card inner ui is kind of distorted
![Screenshot 2024-10-15 001903](https://github.com/user-attachments/assets/dfb5222e-11b9-45a0-8707-10a8131a6808)
the size of button in the booking form is too big sized
![Screenshot 2024-10-15 003035](https://github.com/user-attachments/assets/dd043fe7-9e6f-4758-80d1-89466b810a59)

### Proposed solution

fixing size of button and ui of cards using css 

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Jordian0** [comment]
@justanayush I can contribute in this task.
