### ISSUE TITLE
Fixing and Updating the UI of Share your experience box

### ISSUE THREAD

**Issue by AsifQamar** [PriyaGhosal/BuddyTrail#705]
Fixing the share your experience for better user interface 

<img width="960" alt="Screenshot_217" src="https://github.com/user-attachments/assets/e08c797a-6128-41b3-8bfb-0bc8c07f6df7">

**Comment by akash70629** [comment]
@AsifQamar submit button is missing , add that too

**Comment by akash70629** [comment]
> > @AsifQamar submit button is missing , add that too
> 
> Added, check my PR please and merge it

I'm also a contributor like you bro 😁 I can't merge 😁 I was just about to report the issue, then found your issue .

**Comment by AsifQamar** [comment]
> > > @AsifQamar submit button is missing , add that too
> > 
> > 
> > Added, check my PR please and merge it
> 
> I'm also a contributor like you bro 😁 I can't merge 😁 I was just about to report the issue, then found your issue .

Oh ok
