### ISSUE TITLE
correcting the nav bar .

### ISSUE THREAD

**Issue by Tanushree084** [PriyaGhosal/BuddyTrail#718]
### Describe the feature

hey @PriyaGhosal,
I want to correct the alignment of the nav bar to make it visible clearly.
<img width="956" alt="image" src="https://github.com/user-attachments/assets/5d9028e0-f4e6-43c8-a637-d298d23d1222">

can you please assign me this issue?

### Add ScreenShots

<img width="956" alt="image" src="https://github.com/user-attachments/assets/3e9eb3c9-5035-4d0a-b576-fa6af2377784">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sujal942** [comment]
Hey, can you assign it to me? I'd like to work on this.
