### ISSUE TITLE
Fix user review page

### ISSUE THREAD

**Issue by devarsheecodess** [PriyaGhosal/BuddyTrail#73]
The text in user review and rating page is not visible. Assign me this issue under gssoc-extd label so i can work on it

**Comment by PriyaGhosal** [comment]
@devarsheecodess Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by devarsheecodess** [comment]
![#1](https://github.com/user-attachments/assets/bd6c91aa-82af-475b-b5eb-0f67e3bc6d5f)
