### ISSUE TITLE
fix bug : double navigating bar in home screen

### ISSUE THREAD

**Issue by ananyag309** [PriyaGhosal/BuddyTrail#74]
I think we should remove one for better ui cuz it is unnecessary present
![poiuy](https://github.com/user-attachments/assets/ceb1d31d-2c1a-4c1e-ad60-8c6afb1502c4)

**Comment by PriyaGhosal** [comment]
@ananyag309 Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
