### ISSUE TITLE
Add scroll on top button

### ISSUE THREAD

**Issue by devarsheecodess** [PriyaGhosal/BuddyTrail#75]
![image](https://github.com/user-attachments/assets/c12a18be-498f-4617-bdb1-e90a03fbb392)
instead of this "sroll on top" text, we can add an arrow to it so it looks good. Assign me this issue under gssoc-extd label

**Comment by PriyaGhosal** [comment]
@devarsheecodess Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by devarsheecodess** [comment]
https://github.com/user-attachments/assets/22122285-3316-4e63-9293-83335c425d61

**Comment by Avii-KS** [comment]
Hi @PriyaGhosal  can I be assigned to solve this issue?
This is my first time takin part in an Open Source Contribution and i would love to work on this issue!

**Comment by parul1522** [comment]
I'm interested to solve this issue.Can you please assign this to me?
