### ISSUE TITLE
Improve responsiveness to contact us page

### ISSUE THREAD

**Issue by ananyag309** [PriyaGhosal/BuddyTrail#76]
currently the contact page accept response and confirmation message display on other screen will improve it with a popup confirmation message on same screen for better practice

**Comment by Shivang-v-erm-a** [comment]
can you please assign it to me

**Comment by PriyaGhosal** [comment]
@ananyag309 Thanks for creating the issue in *SkillWise*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

I'm excited to see your contribution as part of *Hacktoberfest 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
