### ISSUE TITLE
Fix booking page

### ISSUE THREAD

**Issue by devarsheecodess** [PriyaGhosal/BuddyTrail#77]
![image](https://github.com/user-attachments/assets/7fb654e0-3184-448e-ad8c-477059aba202)
Poor spacing and styling of the booking page. Plz assign me this issue under gssoc-extd label

**Comment by PriyaGhosal** [comment]
@devarsheecodess Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by devarsheecodess** [comment]
![Screenshot 2024-10-05 234248](https://github.com/user-attachments/assets/13e9b6e0-fa44-47cc-a0d9-47f6d7dedae7)
