### ISSUE TITLE
Proposal for Navbar Redesign

### ISSUE THREAD

**Issue by AyushiTaralkar** [PriyaGhosal/BuddyTrail#78]
**Issue:**  
The current navbar is too big, and the elements are misaligned, leading to a cluttered appearance and a poor user experience.

**Solution:**
1. **Reduce Navbar Size**: Decrease the height of the navbar to create a more compact and visually appealing design.
2. **Element Alignment**: Align all navbar items (links, logos) to ensure consistent spacing and positioning. Use flexbox or grid layout for better alignment.
3. **Font Size Adjustment**: Modify the font size of navbar items to ensure readability while keeping the design sleek.
4. **Consistent Padding and Margins**: Implement uniform padding and margins around each navbar item to maintain visual harmony.
5. **Responsive Design**: Ensure the navbar adapts well on different screen sizes, collapsing into a mobile-friendly version on smaller devices.
6. **Highlight Active Links**: Clearly indicate the active link to enhance navigation clarity for users.

**Benefits:**
- **Improved Usability**: A well-aligned and appropriately sized navbar enhances user navigation and overall experience.
- **Enhanced Aesthetics**: A compact navbar provides a cleaner look and allows more content to be visible on the page.
- **Responsive Interaction**: A responsive design ensures a consistent experience across all devices, improving accessibility and engagement.

This redesign will create a more user-friendly and visually appealing navbar, promoting better navigation and engagement on the website.**

**Comment by PriyaGhosal** [comment]
@AyushiTaralkar Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by AyushiTaralkar** [comment]
issue #78
