### ISSUE TITLE
✨UI FIX✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [PriyaGhosal/BuddyTrail#79]
**I can refactor this page.Can you please assign me this work.**
<img width="440" alt="Screenshot 2024-10-04 at 5 41 37 PM" src="https://github.com/user-attachments/assets/a9334a29-6dbb-45b0-a11b-8bb5bb4955a1">

**Comment by T-Rahul-prabhu-38** [comment]
@PriyaGhosal  can you please assign me this task , i would like to fix this issue and resolve it.

**Comment by PriyaGhosal** [comment]
@T-Rahul-prabhu-38 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by T-Rahul-prabhu-38** [comment]
i had another idea

**Comment by T-Rahul-prabhu-38** [comment]
if i add a local storage base for this will the level be buffed to 3?

local storage base can be proved to be very useful for getting user credentials back and even to store JWT's during authentication and login.
