### ISSUE TITLE
Adding Hover Effect to the Book Now button

### ISSUE THREAD

**Issue by ahinagangopadhyay** [PriyaGhosal/BuddyTrail#80]
I want to add a hover effect to the Book Now button and make the ui of the page better.
![Screenshot (255)](https://github.com/user-attachments/assets/7319f5a0-7448-4813-b157-22738200a168)

Please assign me this issue under Hacktoberfest 2024 and GSSOC Extended 2024

**Comment by Shivang-v-erm-a** [comment]
can you please assign it to me

**Comment by PriyaGhosal** [comment]
@ahinagangopadhyay Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
