### ISSUE TITLE
Could increase the user interactivity and appearance of the "Book a cab or auto" section.

### ISSUE THREAD

**Issue by harinireddy10** [PriyaGhosal/BuddyTrail#81]
![Screenshot 2024-10-04 194031](https://github.com/user-attachments/assets/7b1b11a3-66ee-4313-93dc-3fc74274a452)
We could make it as a real time application by including the fare of the ride and also by adding some interactive css elements.

**Comment by PriyaGhosal** [comment]
@harinireddy10 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
