### ISSUE TITLE
Make review Section attractive

### ISSUE THREAD

**Issue by Kratika-Solanki** [PriyaGhosal/BuddyTrail#83]
As I have checked the website, the review section is not looking very nice and seems to be very unattractive, I can make that section much more attractive from my end.

![image](https://github.com/user-attachments/assets/cf748bdc-d193-44fc-8bbc-0abfebffc5ec)

**Comment by PriyaGhosal** [comment]
@Kratika-Solanki Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
