### ISSUE TITLE
Adding images on the deals and offer cards

### ISSUE THREAD

**Issue by Kratika-Solanki** [PriyaGhosal/BuddyTrail#84]
As I checked that there are no images are added on the cards of deals and offers, I can add images on the card from my end.

![image](https://github.com/user-attachments/assets/1682e9c6-7f13-47f9-904f-4e7b0cdc61d6)

**Comment by PriyaGhosal** [comment]
@Kratika-Solanki Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
