### ISSUE TITLE
BUG: Format inconsistent

### ISSUE THREAD

**Issue by KrishPatel1205** [PriyaGhosal/BuddyTrail#842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The input for the Email and Message field are not the same as the name field and make it look inconsistent and visually displeasing.
<img width="481" alt="Screenshot 2024-10-16 at 8 36 41 PM" src="https://github.com/user-attachments/assets/8513ad75-add9-4789-a2bb-43ab03a9aae2">

It should be fixed to look like this:
<img width="481" alt="Screenshot 2024-10-16 at 8 36 20 PM" src="https://github.com/user-attachments/assets/7f62487f-9322-4b60-b5d2-da0bfd9b21c7">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kiran-F** [comment]
@KrishPatel1205 How you linked your PR over here?
