### ISSUE TITLE
Add "My Trips" Section for Trip Management

### ISSUE THREAD

**Issue by SCR01** [PriyaGhosal/BuddyTrail#92]
### **Description:**
We propose adding a "My Trips" section that enables users to manage their trips more effectively. This feature should include:
- Trip Overview: A summary of all booked trips with details like destination, dates, and booking status.
- Edit Trip Details: Allow users to modify trip information such as dates, accommodations, and activities.
- Trip Reminders: Notifications for upcoming trips, including reminders for check-in, packing lists, and itinerary updates.
- Trip History: A log of past trips for easy reference and rebooking of similar trips.
- Manage Bookings: Options to cancel or reschedule trips directly from the "My Trips" section.

**Comment:**
Adding the "My Trips" section will enhance user convenience by providing a centralized location for trip management. This feature will allow users to keep track of their travel plans, make changes easily, and enjoy a more organized travel experience.

**Comment by PriyaGhosal** [comment]
Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀
