### ISSUE TITLE
Enhance the UI of the Auto Cab Booking Section

### ISSUE THREAD

**Issue by SCR01** [PriyaGhosal/BuddyTrail#93]
### **Description:**

- We propose improvements to the user interface (UI) of the auto cab booking section to enhance user experience. The enhancements should focus on:
- Modern Design: Update the visual design with a clean, modern look that aligns with current UI trends.
- User-Friendly Navigation: Simplify navigation within the section for a more intuitive user experience, making it easy to book rides.
- Real-Time Tracking: Integrate a real-time tracking feature to show the location of booked autos, improving transparency and user confidence.
- Interactive Elements: Use interactive elements (like buttons and sliders) for selecting vehicle options, pick-up/drop-off locations, and payment methods.
- Feedback Mechanism: Incorporate user feedback options for continuous improvement based on user experiences.
### 
**Comment:**
Enhancing the UI of the auto cab booking section will significantly improve user engagement and satisfaction, making it easier and more enjoyable for users to book their rides. A modern and user-friendly interface will lead to increased usage and better overall experiences.

![Screenshot 2024-10-05 024839](https://github.com/user-attachments/assets/d0025484-c60f-475e-97b5-9614112be811)

**Comment by PriyaGhosal** [comment]
@SCR01 Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by shivigoyal4321** [comment]
hi! if this issue is not yet resolved, **kindly assign it to me**, the **layout definitely needs to be corrected, the placeholders are not in correct order** moreover when **asked to select the cab/auto option , after selecting it does not appear their.**
I can fix this, please assign it to me

![Screenshot (32)](https://github.com/user-attachments/assets/56078bcd-23ff-4538-a009-86807892f2ec)

**Comment by SCR01** [comment]
@PriyaGhosal I am working on it!

**Comment by SCR01** [comment]
@PriyaGhosal I will do it before today.
