### ISSUE TITLE
Add nav bar in team page

### ISSUE THREAD

**Issue by Son7c** [PriyaGhosal/BuddyTrail#930]
### Describe the feature

Adding of navbar on team page

### Add ScreenShots

![Screenshot_2024-10-18-07-50-47-80_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/145d6a37-bce1-4832-bc8d-42dc4eeb5e7b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DarshiniKurasa** [comment]
I would like to work on it. Please assign this to me.
