### ISSUE TITLE
BUG:Footer Section

### ISSUE THREAD

**Issue by Bhum-ika** [PriyaGhosal/BuddyTrail#931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/066c07ac-104a-4870-ab12-c2aa61c8056d)

The footer is not well coded some text are very small and they are not aligning well. Kindly assign this issue to me under relevant tags

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by amanreddy77** [comment]
hey @Bhum-ika can you please assign me this I will fix this issue
