### ISSUE TITLE
BUG: Chatbot not working properly

### ISSUE THREAD

**Issue by yashksaini-coder** [PriyaGhosal/BuddyTrail#938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The chatbot is only giving `I'm sorry, I don't understand that.` 

<br>
![image](https://github.com/user-attachments/assets/85711779-a8ad-422e-b521-587a15dfee47)
<br>

I would like to fix that and add more flexible chat messaging, in the chatbot by implementing nested lists concept for better retrieval and more better options. with a custom lists setup to display all the locations that can help users in their travel-planning, and acts as a guide for them.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sunidhi3** [comment]
Please assign this to me i can work on it I'm a GSSoC contributor

**Comment by yashksaini-coder** [comment]
> Please assign this to me i can work on it I'm a GSSoC contributor

Hi @sunidhi3 I just got assigned this issue so I'm currently working on this, Once I am finished you can work later on the chatbot feature
