### ISSUE TITLE
BUG: About section issue

### ISSUE THREAD

**Issue by 4F24L** [PriyaGhosal/BuddyTrail#940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## About Section issue

- The information div should be more wide refer to screen.

![image](https://github.com/user-attachments/assets/e1688f9b-9928-4681-927b-2934ae87e4fd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by amanreddy77** [comment]
hey @4F24L can i take this up ?

**Comment by 4F24L** [comment]
@PriyaGhosal You shouldn't merge other PR. When the issue is already assigned to someone.
