### ISSUE TITLE
CODE CHANGE: Change navbar font size and fix the overlapping structure

### ISSUE THREAD

**Issue by eshwanthkartitr** [PriyaGhosal/BuddyTrail#949]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the code change

in light 
![image](https://github.com/user-attachments/assets/b46ed1d3-b18e-4c68-bd9d-4ed7918a768d)
in dark
![image](https://github.com/user-attachments/assets/8f2decf6-c786-4052-9b4d-a5a2f904841a)
Dark mode fails in personalized recomendations
![image](https://github.com/user-attachments/assets/0eb1ed9c-c5e9-4ee3-a51b-24ed9836c3fa)

### Proposed solution

Changing navbar font size
remove inconsistencies in homepage in both modes
make the theme of the website consistent

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ki1er** [comment]
I can fix it can you assign it to me

**Comment by eshwanthkartitr** [comment]
i have already started working on this issue
