### ISSUE TITLE
Feat: Addition of Navigation bar in About page And Make some changes in that page.

### ISSUE THREAD

**Issue by prachitriv** [PriyaGhosal/BuddyTrail#956]
### Describe the feature

Hey @PriyaGhosal 
The About page should also have a navigation bar, and the page is too simple right now. Therefore, some CSS changes should be made to make the page look more attractive. Please assign this issue to me.

### Add ScreenShots

**Your current page looks like**
![Screenshot (44)](https://github.com/user-attachments/assets/86cb452a-e976-467b-81bd-c81bf7e58cd9)

**After Changes**
![Screenshot (45)](https://github.com/user-attachments/assets/862f9f02-72f2-48de-8ccf-082701c75dc7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sunidhi3** [comment]
Please assign this to me i can work on it I'm a GSSoC contributor
