### ISSUE TITLE
BUG: Inconsistent design

### ISSUE THREAD

**Issue by KrishPatel1205** [PriyaGhosal/BuddyTrail#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The design was applied to certain elements and not to the other. Also the text int he send message button was too small and ruined the appearance of the button along with the text above the form.
<img width="579" alt="Screenshot 2024-10-24 at 8 56 59 PM" src="https://github.com/user-attachments/assets/ba15c75d-8ba9-4be6-ad9e-abd1868867a0">

Should be fixed in order to look like this:
<img width="579" alt="Screenshot 2024-10-24 at 8 56 29 PM" src="https://github.com/user-attachments/assets/623162da-626a-419f-8197-ce7c4ede5d07">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DarshiniKurasa** [comment]
I would like to work on it. Please assign this to me.
