### ISSUE TITLE
CODE CHANGE: Improving the UI of the WHOLE ABOUT  page

### ISSUE THREAD

**Issue by AADESHak007** [PriyaGhosal/BuddyTrail#967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the code change

Hey @PriyaGhosal there are issues raised about particular sections of the about us page .
Currently your About Page doesn't fits the standard of your home page and is being treated like a different part of it .

### Proposed solution

I would have probably raised 2 to 3 issues to do this work but I will do it with a single issue. 
The changes I want to make is  :
1. The navbar is not aligned with the original navbar
2. The page will look more similar to the website 
3. The cards are not treated well , like the hover effect '
4. The footer section will be the same as of other websites  . 
I will do this by today only so you can review the work  .
Please assign this task to me under hacktoberfest and GSSOC-extd

P.S. : Please give labels after you have seen the changes . 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DarshiniKurasa** [comment]
I would like to work on it. Please assign this to me.
