### ISSUE TITLE
BUG: navbar not responsive for 13inch screen

### ISSUE THREAD

**Issue by Neelancy1504** [PriyaGhosal/BuddyTrail#972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Before:
![image](https://github.com/user-attachments/assets/e7e34cd2-7657-416a-9998-1d08773cd7fc)

After:
![image](https://github.com/user-attachments/assets/8fa5e1d7-d686-473c-a104-5de865b0b8ea)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DarshiniKurasa** [comment]
I would like to work on it. Please assign this to me.
