### ISSUE TITLE
Overlapping of Social Media Icons with Scroll to Top Button

### ISSUE THREAD

**Issue by snehhhcodes** [PriyaGhosal/BuddyTrail#99]
# Description:
The social media icons in the footer are currently overlapping with the "scroll to top" button. This overlap makes it difficult for users to access or click on the social icons when scrolling to the bottom of the page.

# Expected Behavior:
The social media icons should be fully visible and clickable, without being obstructed by other elements on the page.

# Proposed Solution:
The issue can be resolved by adjusting the position of icons. By making this change, the icons will remain fully accessible, and users won’t encounter any problems interacting with them.

I've added a video so you can better visualize the issue.

[screen-capture.webm](https://github.com/user-attachments/assets/890f6683-e24f-489e-a735-50baca5bcd4b)

If you find this issue/proposed solution suitable, please assign this to me under the labels of GSSoC and Hacktoberfest and appropriate level.

**Comment by snehhhcodes** [comment]
@PriyaGhosal any update on this?
would be great if you can review it once

**Comment by PriyaGhosal** [comment]
@snehhhcodes Thanks for creating the issue in *BuddyTrail*!!! The issue has been assigned to you.

Before you start working on your PR, please make sure to:

- ⭐ Star the repository if you haven't already.
- Pull the latest changes to avoid any merge conflicts.
- Attach *before & after screenshots* in your PR for clarity.
- Include the *issue number* in your PR description for better tracking.

Contributors will start at Level 1, and their level will increase based on the quality and quantity of their contributions. The more effort and value you bring, the faster you'll progress. Put forth your best effort to unlock new levels and opportunities!

I'm excited to see your contribution as part of *GSSOC EXTENDED 2024*! 🎉  
Don't forget to follow me on GitHub for more updates.

Happy open-source contributing! 🚀

**Comment by snehhhcodes** [comment]
@PriyaGhosal hey Priya just saw the live preview of the project and your latest merged PR solved the issue i was assigned for so  i dont think so i should work on it anymore as the changes are done or should i do it ?

**Comment by vijaychandra1910** [comment]
@PriyaGhosal  please assign it to me, I want to work on it

**Comment by snehhhcodes** [comment]
> @PriyaGhosal please assign it to me, I want to work on it

working on it!!
